////
|metadata|
{
    "name": "scheduler-views",
    "controlName": ["scheduler"],
    "tags": [],
    "guid": "","buildFlags": [],
    "createdOn": "2017-03-30T09:37:02.0484523Z"
}
|metadata|
////

= Views ({SchedulerName})

The topics in this section provide information about the different views used by the {SchedulerName} control to present calendar data.

== Overview

The {SchedulerName} control can be configured to present calendar information in different ways called "views". The view type can be configured using the link:{SchedulerXFLink}.xamscheduler~viewmode.html[ViewMode] property. If you do not specify the `ViewMode` property be default the control will render a month view. You can find more information regarding each view in the topics listed below:

[options="header", cols="a,a"]
|=======
|Topic|Purpose

|link:scheduler-agendaview.html[Agenda View ({SchedulerName})]
|This topic explains how data is presented in the {SchedulerName}'s agenda view.

|link:scheduler-dayview.html[Day View ({SchedulerName})]
|This topic explains how data is presented in the {SchedulerName}'s day view.

|link:scheduler-monthview.html[Month View ({SchedulerName})]
|This topic explains how data is presented in the {SchedulerName}'s month view.

|link:scheduler-weekview.html[Week View ({SchedulerName})]
|This topic explains how data is presented in the {SchedulerName}'s week view.

|=======