////
|metadata|
{
    "name": "excelengine-api-overview",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["API"],
    "guid": "{C5F8A2E9-7CD6-4B00-9EA6-B26EFA48DEA8}",
    "buildFlags": [],
    "createdOn": "2007-04-05T08:18:50Z"
}
|metadata|
////

= API Overview ({SchedulerName})

This section lists each namespace that is relevant to the {SchedulerName}. We also give you several key classes that you will be using while programming with this code library. The namespaces and classes on this page link directly into our API documentation.

ifdef::xamarin[]
[options="header", cols="a,a"]
|====

|Namespace:
|Key Classes:

| * link:{SchedulerCoreLink}_namespace.html[Infragistics.Scheduler]
* link:{SchedulerXFLink}_namespace.html[Infragistics.XamarinForms.Controls.Scheduler]

| * link:{SchedulerXFLink}.xamscheduler.html[{SchedulerClassName}]
* link:{SchedulerXFLink}.schedulelistdatasource.html[ScheduleListDataSource]
* link:{SchedulerCoreLink}.appointment.html[Appointment]
* link:{SchedulerCoreLink}.scheduleresource.html[ScheduleResource]

|====
endif::xamarin[]