////
|metadata|
{
    "name": "piechart-selection",
    "controlName": ["{PieChartName}"],
    "tags": ["Charting","Data Presentation","How Do I"],
    "guid": "",
    "buildFlags": ["SL","WPF","win-phone","WINFORMS","ANDROID","XAMARIN"],
    "createdOn": "2014-06-05T19:53:12.0788999Z"
}
|metadata|
////

= {DataPieChartName}

link:{DataPieChartLink}.{DataPieChartName}.html[{DataPieChartName}] は、セクションに分割された円形の領域で構成される、円チャートを表示する専用のコントロールです。各セクションには、基本データ値に比例する円弧の長さがあります。

{DataPieChartName} コントロールは分類データを表すために使用されます。カテゴリが少ない場合や各カテゴリが全体としてデータの相対的に大きなパーセンテージを構成する場合、これは最も効率的です。

ifdef::wpf[]
{DataPieChartName} コントロールは、Infragistics.WPF.Charts NuGet パッケージ内に存在します。
endif::wpf[]

ifdef::win-forms[]
{DataPieChartName} コントロールは、Infragistics.WinForms.Charts NuGet パッケージ内に存在します。
endif::win-forms[]

== link:data-pie-chart-getting-started.html[{DataPieChartName} を使用した作業の開始]

{DataPieChartName} コントロールを使用してすばやく作業を開始するためのコントロールの使用方法を提供します。

== link:data-pie-chart-configuration.html[{DataPieChartName} の構成]

このセクションには、{DataPieChartName} コントロールで提供される主要な特徴および機能についての情報が含まれています。


== link:data-pie-chart-api-overview.html[API の概要]

このトピックは、{DataPieChartName} コントロールを使用して開発する際の名前空間とクラスについて説明します。