////
|metadata|
{
    "name": "datachart-series",
    "controlName": ["{DataChartName}"],
    "tags": ["Charting","Data Binding","Getting Started"],
    "guid": "3d087135-84b0-4f6e-b3eb-afe7e962e406",
    "buildFlags": [],
    "createdOn": "2014-06-05T19:39:00.6883931Z"
}
|metadata|
////

= Chart Series

=== Purpose
This topic introduces the concept of chart's link:{DataChartLink}.series.html[Series] objects and guides you to the discussion of types of series, data binding, and series' requirements.

The link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ control provides pick:[xaml,win-forms="link:{DataChartLinkBase}.{DataChartBase}{ApiProp}Series.html[Series]"]  
pick:[android="link:{DataChartLinkBase}.~addseries.html[AddSeries]"] {ApiMember} that allows adding link:{DataChartLink}.series.html[Series] objects to chart plot area. You can add different chart series and display multiple data sources in the same chart control and thus create composite chart. Each series that is added to the chart should have appropriate binding set to data members and axis types.

== Data Binding

All types of link:{DataChartLink}.series.html[Series] have link:{DataChartLink}.Series~{ApiDataSource}.html[{ApiDataSource}] property for binding to data source. Some series require more than one data column or property for each data item in order to render correctly. Therefore, there is no common data mapping property for all Series. Instead, the process of data mapping to Series is accomplished using the Series object’s unique `*MemberPath` properties.

== link:datachart-series-types.html[Series Types] 

When multiple Series are added to the chart control, each successive series will be layered on top of the previous series starting from the first to the last series. This allows easy composite creation of different types of chart series. However, there are some restrictions on which types of chart series that can be used together. For more information on this please read the appropriate link:datachart-series-types.html[Series Types] and link:datachart-multiple-series.html[Adding Multiple Series] sections.

== link:datachart-series-requirements.html[Series Requirements] 
The chart control supports a number of various series and some series have specific requirements that need to be met. Please refer to the link:datachart-series-requirements.html[Series Requirements] article for more information on series requirements.

ifdef::wpf,win-universal,xamarin,win-forms[]
== Legend 

The link:{DataChartLink}.series{ApiProp}legend.html[Legend] property of a Series determines which link:{DataChartLink}.{LegendName}.html[{LegendName}] will list the Legend Item representing link:{DataChartLink}.series{ApiProp}title.html[Title] of the Series as well as it legend badge.  
endif::wpf,win-universal,xamarin,win-forms[]

== Related Content

This section provides you with useful information about task-based procedures on working with series of the {DataChartName} control.

ifdef::sl,wpf[]
* link:datachart-creating-custom-series.html[Creating Custom Series]
endif::sl,wpf[]

* link:datachart-multiple-series.html[Adding Multiple Series]

ifdef::sl,wpf,win-phone[]
* link:datachart-series-data-correlation.html[Series Data Correlation]
endif::sl,wpf,win-phone[]

ifdef::sl,wpf,win-phone[]
* link:datachart-series-error-bars.html[Series Error Bars]
endif::sl,wpf,win-phone[]

* link:datachart-trend-lines.html[Series Trend Lines]

ifdef::sl,wpf,win-universal[]
* link:datachart-series-highlighting.html[Series Highlighting]
endif::sl,wpf,win-universal[]

* link:datachart-series-requirements.html[Series Requirements]
* link:datachart-series-types.html[Series Types]