////
|metadata|
{
    "name": "datachart-chart-navigation",
    "controlName": ["{DataChartName}"],
    "tags": ["Application Scenarios","Charting","How Do I"],
    "guid": "06c9eed5-3dd5-4dcf-a7b2-151cb5b2bff9",
    "buildFlags": [],
    "createdOn": "2014-06-05T19:39:00.661382Z"
}
|metadata|
////

= Chart Navigation

== Topic Overview

=== Purpose

This topic demonstrates, with code examples, the navigation use properties in the link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ control and their use.

=== Required background

The following table lists the topics required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:datachart-datachart.html[{DataChartName}]
|This topic provides an overview of key features in the _{DataChartName}_ control.

|====

=== In this topic

This topic contains the following sections

* <<Introduction,Introduction>>
* <<CodeExample,Code Example>>
ifdef::wpf[]
* <<DragSnippet, Code Snippet for DragModifier set to Shift OR Control>>
endif::wpf[]
* <<RelatedContent,Related Content>>

[[Introduction]]
== Introduction

In the {DataChartName} control, chart navigation is disabled by default. Follow the instructions in the this section in order to enable it. The property configuration shown in the Recommended Value column in the table below, enables chart navigation
ifdef::xaml[]
and displays the navigation zoom bars in the chart.
endif::xaml[]
ifdef::win-forms[]
allow end users to zoom in and out with mouse interaction.
endif::win-forms[]

[options="header", cols="a,a,a,a,a"]
|====
|Property Name|Type|Description|Default Value|Recommended Value

ifdef::sl,wpf,win-universal[]
| link:{DataChartLinkBase}.{DataChartBase}{ApiProp}defaultinteraction.html[DefaultInteraction]
|InteractionState
|Configures whether mouse dragging within the chart plot area will zoom or pan the content of chart. The valid values are 

* DragZoom 

* DragPan 

* None 

|DragZoom
|DragZoom
endif::sl,wpf,win-universal[]

| link:{DataChartLink}.{DataChartName}{ApiProp}IsHorizontalZoomEnabled.html[IsHorizontalZoomEnabled]
|Boolean
|When True, enables horizontal zooming of the chart.
|False
|True

ifdef::sl,wpf,win-universal[]
| link:{DataChartLink}.{DataChartName}{ApiProp}horizontalzoombarvisibility.html[HorizontalZoombarVisibility]
|Visibility
|Changes visiblity of the horizontal zoom bar in the chart.
|Collapsed
|Visible
endif::sl,wpf,win-universal[]

| link:{DataChartLink}.{DataChartName}{ApiProp}isverticalzoomenabled.html[IsVerticalZoomEnabled]
|Boolean
|When True, enables vertical zooming of the chart.
|False
|True

ifdef::sl,wpf[]
| link:{DataChartLink}.{DataChartName}{ApiProp}verticalzoombarvisibility.html[VerticalZoombarVisibility]
|Visibility
|Changes visiblity of the vertical zoom bar in the chart.
|Collapsed
|Visible
endif::sl,wpf[]

ifdef::wpf[]
| link:infragisticswpf.controls.charts.xamdatachart~infragistics.controls.seriesviewer~dragmodifier.html[DragModifier]
|ModifierKey
|Sets the modifier key to use to trigger zooming.
|None
|Control
endif::wpf[]

ifdef::wpf[]
| link:infragisticswpf.controls.charts.xamdatachart~infragistics.controls.seriesviewer~panmodifier.html[PanModifier]
|ModifierKey
|Sets the modifier key to use to trigger panning.
|Shift
|Shift
endif::wpf[]

|====

[[CodeExample]]
== Code Example

The following code snippet demonstrates how to enable chart navigation in the {DataChartName} control.

ifdef::xaml[]

*In XAML:*

----
<ig:{DataChartName} x:Name="Chart" 
                IsHorizontalZoomEnabled="True" 
                IsVerticalZoomEnabled="True">
</ig:{DataChartName}>
----

endif::xaml[]

ifdef::wpf[]

*In Visual Basic:*

----
Dim chart As New {DataChartName}()
chart.IsHorizontalZoomEnabled = true
chart.IsVerticalZoomEnabled = true
----

endif::wpf[]

ifdef::win-forms[]

*In Visual Basic:*

----
Dim chart As New {DataChartName}()
chart.IsHorizontalZoomEnabled = true
chart.IsVerticalZoomEnabled = true
----

endif::win-forms[]

ifdef::wpf[]

*In C#:*

----
var chart = new {DataChartName}();
chart.IsHorizontalZoomEnabled = true;
chart.IsVerticalZoomEnabled = true;
----

endif::wpf[]

ifdef::win-forms[]

*In C#:*

----
var chart = new {DataChartName}();
chart.IsHorizontalZoomEnabled = true;
chart.IsVerticalZoomEnabled = true;
----

endif::win-forms[]

ifdef::xamarin[]

*In C#:*

----
var chart = new {DataChartName}();
chart.IsHorizontalZoomEnabled = true;
chart.IsVerticalZoomEnabled = true;
----

endif::xamarin[]

ifdef::android[]

*In Java:*

[source,js]
----
DataChartView chart = new DataChartView();
chart.setIsHorizontalZoomEnabled(true);
chart.setIsVerticalZoomEnabled(true);
----

endif::android[]

ifdef::wpf[]

[[DragSnippet]]
== Code Snippet for DragModifier set to Shift OR Control
Sometimes, you may want to allow multiple modifier keys to trigger the behavior. To achieve this you should handle the {DataChartName}'s PreviewKeyDown event and write some logic to change the `DragModifier` or `PanModifier` based on the key being pressed. Please see the code snipper below for an example.

*In C#:*
[source,csharp]
----
private void xamDataChart1_PreviewKeyDown(object sender, KeyEventArgs e)
{
    if (e.Key == Key.LeftShift | e.Key == Key.RightShift)
    {
        (sender as XamDataChart).DragModifier = ModifierKeys.Shift;
    }
    if (e.Key == Key.LeftCtrl | e.Key == Key.RightCtrl)
    {
        (sender as XamDataChart).DragModifier = ModifierKeys.Control;
    }
}
----

*In Visual Basic:*
[source,vb]
----
Public Sub XamDataChart1_PreviewKeyDown(ByVal sender As Object, ByVal e As KeyEventArgs)

    If e.Key = Key.LeftShift OrElse e.Key = Key.RightShift Then
        CType(sender, XamDataChart).DragModifier = ModifierKeys.Shift
    End If
    If e.Key = Key.LeftCtrl OrElse e.Key = Key.RightCtrl Then
        CType(sender, XamDataChart).DragModifier = ModifierKeys.Control
    End If

End Sub
----

endif::wpf[]

[[RelatedContent]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
| *Topic* | *Purpose* 

| link:datachart-navigating-chart-using-code.html[Navigating Chart Using Code]
|This topic provides information on how to navigate chart in code-behind

ifdef::sl,wpf,win-universal,win-forms[]
| link:datachart-navigating-chart-using-moue-and-keyboard.html[Navigating Chart Using Mouse and Keyboard]
|This topic provides information on how to navigate chart using mouse and keyboard
endif::sl,wpf,win-universal,win-forms[]

ifdef::android,xamarin,wpf,win-phone,win-universal,win-forms[]
| link:datachart-navigating-chart-using-touch-gestures.html[Navigating Chart Using Touch Gestures]
|This topic provides information on how to navigate chart using touch gestures
endif::android,xamarin,wpf,win-phone,win-universal,win-forms[]

ifdef::sl,wpf[]
| link:datachart-navigating-chart-using-overview-plus-detail-pane.html[Navigating Chart Using Overview Plus Detail Pane]
|This topic provides information on how to navigate chart using the Overview Plus Detail Pane
endif::sl,wpf[]

|====