////

|metadata|
{
    "name": "datachart-markers",
    "controlName": ["{DataChartName}"],
    "tags": [],
    "guid": "7f4ee028-93ca-4274-a199-f076bf4ebd87",  
    "buildFlags": [],
    "createdOn": "2014-06-05T19:39:00.6843917Z"
}
|metadata|
////

= Chart Markers

Markers are visual elements that display the values of data points on the link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ control's plot area. Markers help your end users immediately identify a data point's value even if the value falls between major or minor grid lines. All link:datachart-series.html[Chart Series] types that inherit from link:{DataChartLink}.markerseries.html[MarkerSeries] class provide various Marker properties that you can set to customize their appearance and shape.

This section provides you with useful information about task-based procedures on working with the {DataChartName} control's Markers.

* link:datachart-customizing-markers.html[Customizing Markers]

ifdef::wpf,win-universal[]
* link:datachart-displaying-marker-values.html[Displaying Marker Values]

endif::wpf,win-universal[]