////

|metadata|
{
    "name": "datachart-saving-a-chart-to-an-image",
    "controlName": [],
    "tags": [],
    "guid": "bfc0a55e-af44-4a3f-af73-32497caa269e",  
    "buildFlags": ["WINFORMS"],
    "createdOn": "2015-09-03T20:10:56.2029124Z"
}
|metadata|
////

= Saving a Chart to an Image

== Topic Overview

=== Purpose

This topic demonstrates the usage of the SaveTo method of the link:datachart-datachart.html[UltraDataChart].

=== Required Background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| _link:datachart-datachart.html[{DataChartName}]_ 
|This topic provides a general overview of the _UltraDataChart_ control

| link:datachart-getting-started-with-datachart.html[Getting Started with Data Chart]
|This topic provides information on how to get started with the _UltraDataChart_ control.

| link:datachart-series-requirements.html[Series Requirements]
|This topic provides information on requirements of Series objects in the UltraDataChart control.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref429040863,Configuring Feature>>

** <<_Ref421266503,Overview>>
** <<_Ref429040869,Code Example>>

* <<_Ref429040884,Related Content>>

[[_Configuring_a_Custom]]
[[_Ref386478097]]
[[_Ref429040863]]
== Configuring Feature

[[_Ref421266503]]

=== Overview

The SaveTo method of the UltraDataChart can be used to render the chart’s image to a file or a stream.

[[_Ref429040869]]

=== Code Example

The following are code snippets demonstrating how to use the SaveTo functionality of the  _UltraDataChart._

To save to a file, a path and an image format need to be specified. The following line of code saves the chart to a JPEG image file:

*In C#:*

[source,csharp]
----
this.ultraDataChart1.SaveTo("chart.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg);
----

*In Visual Basic:*

[source,vb]
----
Me.UltraDataChart1.SaveTo("chart.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg)
----

The chart's binary image data can also be saved to a stream. In this case, the stream and the image format must be specified:

*In C#:*

[source,csharp]
----
this.ultraDataChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
----

*In Visual Basic:*

[source,vb]
----
Me.UltraDataChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg)
----

[[_Ref429040884]]

=== Related Content

The following topics provide additional information related to this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| _link:datachart-datachart.html[{DataChartName}]_ 
|This topic provides a general overview of the _UltraDataChart_ _._

| _link:datachart-getting-started-with-datachart.html[Getting Started with Data Chart]_ 
|This topic provides information on how to get started with the _UltraDataChart_ .

| link:datachart-series-requirements.html[Series Requirements]
|This topic provides information on requirements of Series objects in the _UltraDataChart_ .

|====