////
|metadata|
{
    "name": "datachart-transition-in-animations",
    "tags": ["Getting Started","How Do I"],
    "controlName": ["{DataChartName}"],
    "guid": "e7671634-cd16-4022-8ba5-0535aa789308",
    "buildFlags": ["wpf","win-universal"],
    "createdOn": "2014-06-05T19:45:38.0668069Z"
}
|metadata|
////

= Chart Transition-In Animations

== Topic Overview

=== Purpose

This topic provides information on enabling the link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ controls transition-in animation feature along with a listing of the supported series.

=== Required background

The following topic is a prerequisite to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:datachart-getting-started-with-datachart.html[Getting Started with {DataChartName}]
|This topic demonstrates how to provide a simple Data Object Model to the _{DataChartName}_ control .

|====

=== In this topic

This topic contains the following sections:

* <<_Ref368408265,Introduction>>

** <<_Ref368408282,Overview>>
** <<_Ref368408307,Supported series>>
** <<_Ref368065506,Supported transition types>>
** <<_Ref368408334,Supported transition speed types>>
** <<_Ref368408345,Supported easing function types>>

* <<_Ref368408391,Configuring the Transition-In Animations>>

** <<_Ref368408402,Overview>>
** <<_Ref368408409,Example>>

* <<_Ref368408420,Related Content>>

** <<_Ref368408431,Topics>>

[[_Ref368408265]]
== Introduction

[[_Ref368408282]]

=== Overview

This feature allows you to animate the series as it loads a new data source. The available animation differs depending on the type of series involved. For example, the link:{DataChartLink}.columnseries_members.html[ColumnSeries] animates by rising from the x-axis, a link:{DataChartLink}.lineseries_members.html[LineSeries] animates by drawing from the y-axis.

By default, animated transitions are disabled and you can enable transition-in animations by setting the link:{DataChartLink}.categoryseries{ApiProp}istransitioninenabled.html[IsTransitionInEnabled] property to  _"True"_  .

Animated transitions can be configured in terms of transition type, speed of the individual data points relative to each other, and the easing transition (managed by an easing function).

[[_Ref368408307]]

=== Supported series

The following series types support the transition-in animations feature:

* link:datachart-category-series-overview.html[Category Series]
* link:datachart-category-range-area-series.html[Range Category Series]
* link:datachart-series-financial-price-series-overview.html[Financial Series]
* link:datachart-financial-indicators-overview.html[Financial Indicators]

[[_Ref368065506]]

=== Supported transition types

Many types of animated transitions are supported based on the nature of the movement and its direction:

* FromZero – Series transitions in from the reference value of the value axis.
* Accordion-type transitions:

** From side:

*** AccordionFromLeft – Series accordions in from the left.
*** AccordionFromRight – Series accordions in from the right.
*** AccordionFromTop – Series accordions in from the top.
*** AccordionFromBottom – Series accordions in from the bottom.

** From an axis:

*** AccordionFromCategoryAxisMinimum – Series accordions in from the category axis minimum.
*** AccordionFromCategoryAxisMaximum – Series accordions in from the category axis maximum.
*** AccordionFromValueAxisMaximum – Series accordions in from the value axis maximum.
*** AccordionFromValueAxisMinimum – Series accordions in from the value axis minimum.

* Expand – Series expands from the value midpoints.
* Sweep-type transitions:

** From side:

*** SweepFromLeft – Series sweeps in from the left
*** SweepFromRight – Series sweeps in from the right
*** SweepFromTop – Series sweeps in from the top.
*** SweepFromBottom – Series sweeps in from the bottom.
*** SweepFromCenter – Series sweeps in from the center.

** From an axis:

*** SweepFromCategoryAxisMaximum – Series sweeps in from the category axis maximum.
*** SweepFromCategoryAxisMinimum – Series sweeps in from the category axis minimum.
*** SweepFromValueAxisMaximum – Series sweeps in from the value axis maximum.
*** SweepFromValueAxisMinimum – Series sweeps in from the value axis minimum.

[[_Ref368408334]]

=== Supported transition speed types

The transition’s speed type determines the speed of the individual items of the current series’s transition relative to each other as the animated transition is playing. The following are the different speed types:

* Auto – Automatically selects a speed type.
* IndexScaled – Data points arrive later if their index is further from the axis origin.
* Normal – All speeds are normal, data points arrive at the same time.
* Random – Data points arrive at random times.
* ValueScaled - Data points arrive later if their value is further from the starting point.

[[_Ref368408345]]

=== Supported easing function types

The easing function determines what way the animation initially eases in. Apply any easing function. It is set to CubicEase by default.

[[_Configuring_the_Transition]]
[[_Ref368408391]]
== Configuring the Transition-In Animations

[[_Ref368408402]]

=== Overview

The transition type is configured by setting the link:{DataChartLink}.categoryseries{ApiProp}transitioninmode.html[TransitionInMode] property to the desired transition name. Automatic selection of the transition type based on the series type is possible, too, by setting the property to  _"Auto"_   (default).

[[_Ref368408409]]

=== Example

The following example demonstrates how to enable transition in animations and have the column series accordion in from the right as a result of the following settings:

[options="header", cols="a,a"]
|====
|Property|Value

| link:{DataChartLink}.categoryseries{ApiProp}istransitioninenabled.html[IsTransitionInEnabled]
| _"True"_ 

| link:{DataChartLink}.series{ApiProp}transitioninspeedtype.html[TransitionInSpeedType]
| _"IndexScaled"_ 

| link:{DataChartLink}.series{ApiProp}transitionineasingfunction.html[TransitionInEasingFunction]
| _"CubicEase"_ 

|====

Following is the code that implements this example:

ifdef::wpf,win-universal[]

*In XAML:*

[source,xaml]
----
<ig:{DataChartName} x:Name="Chart" >
    <ig:{DataChartName}.Series>
        <ig:ColumnSeries IsTransitionInEnabled="True"
            TransitionInSpeed="IndexSpeed">
            <ig:ColumnSeries.TransitionInEasingFunction>
                <CubicEase />
            </ig:ColumnSeries.TransitionInEasingFunction>
        </ig:ColumnSeries>
    </ig:{DataChartName}.Series>
</ig:{DataChartName}>
----

endif::wpf,win-universal[]

ifdef::xamarin[]

*In XAML:*

[source,xaml]
----
<ig:XamDataChart x:Name="Chart" >
    <ig:XamDataChart.Series>
        <ig:ColumnSeries IsTransitionInEnabled="True"
            TransitionInSpeed="IndexSpeed">
            <ig:ColumnSeries.TransitionInEasingFunction>
                <CubicEase />
            </ig:ColumnSeries.TransitionInEasingFunction>
        </ig:ColumnSeries>
    </ig:XamDataChart.Series>
</ig:XamDataChart>
----

endif::xamarin[]

ifdef::wpf[]

*In C#:*

[source,csharp]
----
var series = new ColumnSeries();
series.IsTransitionInEnabled = true;
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed;  
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase;
----

endif::wpf[]

ifdef::win-forms[]

*In C#:*

[source,csharp]
----
var series = new ColumnSeries();
series.IsTransitionInEnabled = true;
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed;  
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase;
----

endif::win-forms[]

ifdef::xamarin[]

*In C#:*

[source,csharp]
----
var series = new ColumnSeries();
series.IsTransitionInEnabled = true;
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed;  
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase;
----

endif::xamarin[]

ifdef::wpf[]

*In Visual Basic:*

[source,vb]
----
Dim series As New ColumnSeries() 
series.IsTransitionInEnabled = true
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase
----

endif::wpf[]

ifdef::win-forms[]

*In Visual Basic:*

[source,vb]
----
Dim series As New ColumnSeries() 
series.IsTransitionInEnabled = true
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase
----

endif::win-forms[]

ifdef::xamarin[]

*In Visual Basic:*

[source,vb]
----
Dim series As New ColumnSeries() 
series.IsTransitionInEnabled = true
series.TransitionInSpeed = TransitionInSpeedType.IndexSpeed
series.TransitionInEasingFunction = System.Windows.Media.Animation.CubicEase
----

endif::xamarin[]

ifdef::android[]

*In Java:*

[source,js]
----
ColumnSeries series = new ColumnSeries();
series.setIsTransitionInEnabled(true);
series.setTransitionInEasingFunction(EasingFunction.CubicEase);
series.setTransitionInSpeed(TransitionInSpeedType.IndexSpeed);
----

endif::android[]

[[_Configuring_the_Transition_1]]
[[_Ref368686978]]
[[_Ref368408420]]
== Related Content

[[_Ref368408431]]
=== Topics

The following topic provides additional information related to this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:datachart-using-datachart.html[Configuring {DataChartName}]
|This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the {DataChartName}™ control.

|====