////

|metadata|
{
    "name": "datachart-working-with-multi-dimensional-data-(olap-data)-(xamdatachart)",
    "controlName": ["{DataChartName}"],
    "tags": ["Application Blocks","Charting","Drilldown","How Do I"],
    "guid": "33c32645-298d-4260-84eb-2fcf28872b60",  
    "buildFlags": ["SL","WPF"],
    "createdOn": "2014-06-05T19:39:00.5723466Z"
}
|metadata|
////

= Working With Multi-Dimensional Data (OLAP Data) in Chart

=== Introduction

This section explains the specifics of using the  _{DataChartName}_™ control with multi-dimensional data (Online Analytical Processing (OLAP) data.

=== Topics

Detailed information regarding visualizing OLAP data in the  _{DataChartName}_   is covered in the following topics:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:datachart-visualizing-multi-dimensional-data-(olap-data)-({DataChartName}).html[Visualizing Multi-Dimensional Data (OLAP Data) ({DataChartName})]
|This topic explains, with code examples, how to display multi-dimensional data (OLAP data) in the _{DataChartName}_ control.

| link:datachart-customizing-series-when-used-with-multi-dimensional-data-(olap-data)-({DataChartName}).html[Customizing Series When Used With Multi-Dimensional Data (OLAP Data) ({DataChartName})]
|This topic explains how to display multiple series types in one chart or to use stacked series when working with multi-dimensional data (OLAP data) in the _{DataChartName}_ control.

|====