////
|metadata|
{
    "name": "resources-sample-polar-data",
    "controlName": [],
    "tags": [],
    "guid": "7ff5fc20-59ee-4d76-ab7c-a63372b95ae5",
    "buildFlags": [],
    "createdOn": "2014-09-24T18:11:06.2533921Z"
}
|metadata|
////

= Sample Polar Data
 
=== Purpose

This topic provides sample data and data models for use with the link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ control and its link:datachart-polar-series-overview.html[Polar Series] types.

=== In this topic
 
This topic contains the following sections:

* <<RequiredNamespaces,Required Namespaces>>
* <<DataModel,Data Model>>
* <<DataSource,Data Source>>  

[[RequiredNamespaces]]
=== Required Namespaces
 
ifdef::wpf,win-universal,win-forms,xamarin[]
*In C#:*
[source,csharp]
----
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel; 
using System.ComponentModel;
using System.Linq;

namespace Infragistics.Models
{
  // TODO add data model
  // TODO add data source 
}
----
endif::wpf,win-universal,win-forms,xamarin[]

ifdef::wpf,win-universal,win-forms[]
*In Visual Basic:*
[source,vb]
----
Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel
Imports System.Linq 

Namespace Infragistics.Models
   ' TODO add data model
   ' TODO add data source
End Namespace
----
endif::wpf,win-universal,win-forms[]

ifdef::android[]
In Java:*
[source,java]
----
import java.util.ArrayList;
import java.util.Random;

// TODO add data model
// TODO add data source 
----
endif::android[]


[[DataModel]]
=== Data Model

ifdef::wpf,win-universal,win-forms,xamarin[]
*In C#:*
[source,csharp]
----

public class PolarDataPoint
{   
    public double Angle { get; set; }
    public double Radius { get; set; } 
}
----
endif::wpf,win-universal,win-forms,xamarin[]


ifdef::wpf,win-universal,win-forms[]
*In Visual Basic:*
[source,vb]
----

Public Class PolarDataPoint 
    Public Property Angle As Double
    Public Property Radius As Double 
End Class
----
endif::wpf,win-universal,win-forms[]


ifdef::android[]
*In Java:*
[source,java]
----
public class PolarDataPoint  
{
    private double _radius;
    public double getRadius(){
        return _radius;
    }
    public double setRadius(double value) {
        _radius = value;
        return _radius;
    }
    private double _angle;
    public double getAngle(){
        return _angle;
    }
    public double setAngle(double value) {
        if(_angle == value){
            return 0;
        }
        _angle = value;
        OnPropertyChanged("Angle");
        return _angle;
    }
    public PolarDataPoint(double angle, double radius){
        _angle = angle;
        _radius = radius;
    }
}
----
endif::android[]


[[DataSource]]
=== Data Source

ifdef::wpf,win-universal,win-forms,xamarin[]
*In C#:*
[source,csharp]
----
public class PolarDataSource : List<PolarDataPoint>
{
    public PolarDataSource()
    {
        this.Add(new PolarDataPoint { Angle = 0, Radius = 80 });
        this.Add(new PolarDataPoint { Angle = 30, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 45, Radius = 40 });
        this.Add(new PolarDataPoint { Angle = 60, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 90, Radius = 80 });
        this.Add(new PolarDataPoint { Angle = 120, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 135, Radius = 40 });
        this.Add(new PolarDataPoint { Angle = 150, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 180, Radius = 20 });
        this.Add(new PolarDataPoint { Angle = 210, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 225, Radius = 40 });
        this.Add(new PolarDataPoint { Angle = 240, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 270, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 300, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 315, Radius = 40 });
        this.Add(new PolarDataPoint { Angle = 330, Radius = 60 });
        this.Add(new PolarDataPoint { Angle = 360, Radius = 80 });
    }
}
----
endif::wpf,win-universal,win-forms,xamarin[]

ifdef::wpf,win-universal,win-forms[]
*In Visual Basic:*
[source,vb]
----
Public Class PolarDataSource Inherits List(Of PolarDataPoint)
    Public Sub New()
        Me.Add(New PolarDataPoint() With { .Angle = 0, .Radius = 80 })
        Me.Add(New PolarDataPoint() With { .Angle = 30, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 45, .Radius = 40 })
        Me.Add(New PolarDataPoint() With { .Angle = 60, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 90, .Radius = 80 })
        Me.Add(New PolarDataPoint() With { .Angle = 120, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 135, .Radius = 40 })
        Me.Add(New PolarDataPoint() With { .Angle = 150, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 180, .Radius = 20 })
        Me.Add(New PolarDataPoint() With { .Angle = 210, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 225, .Radius = 40 })
        Me.Add(New PolarDataPoint() With { .Angle = 240, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 270, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 300, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 315, .Radius = 40 })
        Me.Add(New PolarDataPoint() With { .Angle = 330, .Radius = 60 })
        Me.Add(New PolarDataPoint() With { .Angle = 360, .Radius = 80 })
    End Sub
End Class
----
endif::wpf,win-universal,win-forms[]
  

ifdef::android[]
*In Java:*
[source,java]
----
public class PolarDataSource extends ArrayList<PolarDataPoint>
{
    public PolarDataSource()
    {
        this.add(new PolarDataPoint(0,80));
        this.add(new PolarDataPoint(30,60));
        this.add(new PolarDataPoint(45,40));
        this.add(new PolarDataPoint(60,60));
        this.add(new PolarDataPoint(90,80));
        this.add(new PolarDataPoint(120,60));
        this.add(new PolarDataPoint(135,40));
        this.add(new PolarDataPoint(150,60));
        this.add(new PolarDataPoint(180,20));
        this.add(new PolarDataPoint(210,60));
        this.add(new PolarDataPoint(225,40));
        this.add(new PolarDataPoint(240,60));
        this.add(new PolarDataPoint(270,60));
        this.add(new PolarDataPoint(300,60));
        this.add(new PolarDataPoint(315,40));
        this.add(new PolarDataPoint(330,60));
        this.add(new PolarDataPoint(360,80));
    }
}
----
endif::android[]