= セルとレコードの選択

このトピックでは、link:{DataGridLink}.{DataGridName}.html[{DataGridName}] コントロールでセルとレコードの選択を構成するプロセスの手順を追って説明します。

== このトピックの内容

このトピックは、以下のセクションで構成されます。

* <<ReqBackground,前提条件>>
* <<Overview,概要>>
* <<SelectionMode,SelectionMode プロパティ>>

[[ReqBackground]]
== 前提条件

本トピックの理解を深めるために、以下のトピックを参照することをお勧めします。

|===
|トピック|目的

|link:datagrid-getting-started-with-grid.html[{DataGridName} を使用した作業の開始] 
|このトピックでは、{DataGridName} コントロールをビューに追加し、サンプル データを生成するために必要な基本的な手順を紹介します。

|link:datagrid-working-with-columns.html[列の作業]
|このトピックでは、{DataGridName} コントロールの列を操作する際のコード例を紹介します。

|===

[[Overview]]
== 概要

{DataGridName} コントロールは、選択の処理方法を変更する機能をサポートします。 

データ グリッドでの選択は行およびセル レベルで有効になり、グリッドの `SelectionMode` オプションを使用して構成できます。このプロパティには、以下にリストされている 5 つの異なるオプションがあります。

セルと行の選択を同時に有効にすることはできません。

* SingleCell - 単一セルの選択が有効になります。
* SingleRow 単一行の選択が有効になります。
* MultipleCell - 複数セルの選択が有効になります。
* MultipleRow - 複数行の選択が有効になります。
* RangeCell - クリックとドラッグの操作による複数セル範囲の選択が有効になります。
MultipleRow または MultipleCell に設定すると、複数行またはセルを選択する時に CTRL キーを押す必要はありません。各行/セルは、その特定の行/セルをクリックしたときに選択または選択解除されます。
* None - セルと行の選択を無効にします。


*XAML の場合:*
[source, xaml]
----
xmlns:ig="clr-namespace:{DataGridNamespace};assembly={ApiPlatform}DataGrid"
...
<ig:{DataGridName} SelectionMode="SingleCell">
</ig:{DataGridName}>
----
endif::xamarin[]

*C# の場合:*
[source, csharp]
----
{DataGridName} grid = new {DataGridName}() {            
        SelectionMode = GridSelectionMode.SingleCell 
};

----

[[RelatedContent]]
== 関連コンテンツ

以下の表は、このトピックに関連するトピックを示します。

|===
|トピック|目的

|行のグループ化

|このトピックでは、{DataGridName} コントロールで行のグループ化のコード例を紹介します。

|===