////

|metadata|
{
    "name": "datachart-saving-a-chart-to-an-image",
    "controlName": [],
    "tags": [],
    "guid": "bfc0a55e-af44-4a3f-af73-32497caa269e",  
    "buildFlags": ["WINFORMS"],
    "createdOn": "2015-09-03T20:10:56.2029124Z"
}
|metadata|
////

= チャートを画像に保存

== トピックの概要

=== 目的

このトピックは、 link:datachart-datachart.html[UltraToolbarsManager] の SaveTo プロパティの使用方法を示します。

=== 前提条件

本トピックの理解を深めるために、以下のトピックを参照することをお勧めします。

[options="header", cols="a,a"]
|====
|トピック|目的

| _link:datachart-datachart.html[{DataChartName}]_ 
|このトピックでは、 _{DataChartName}_ コントロールの概要を説明します。

| link:datachart-getting-started-with-datachart.html[データ チャートを使用した作業の開始]
|このトピックでは、 _UltraDataChart_ コントロールを使用して作業を開始する方法に関する情報を提供します。

| link:datachart-series-requirements.html[シリーズ要件]
|このトピックでは、UltraDataChart コントロールで利用可能な散布シリーズに関する情報を提供します。

|====

=== このトピックの内容

このトピックは、以下のセクションで構成されます。

* <<_Ref429040863,機能の構成>>

** <<_Ref421266503,概要>>
** <<_Ref429040869,コード例>>

* <<_Ref429040884,関連コンテンツ>>

[[_Configuring_a_Custom]]
[[_Ref386478097]]
[[_Ref429040863]]
== 機能の構成

[[_Ref421266503]]

=== 概要

UltraDataChart の SaveTo メソッドは、チャート画像をファイルやストリームに描画するために使用できます。

[[_Ref429040869]]

=== コード例

以下は、 _UltraDataChart_   の SaveTo 機能を使用方法を示すコード スニペットです。

ファイルを保存するには、パスと画像形式を指定する必要があります。以下のコードは、JPEG 画像ファイルにチャートを保存します。

*C# の場合:*

[source,csharp]
----
this.ultraDataChart1.SaveTo("chart.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg);
----

*Visual Basic の場合:*

[source,vb]
----
Me.UltraDataChart1.SaveTo("chart.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg)
----

チャートのバイナリ画像データはストリームに保存することも可能です。その場合は、ストリームと画像形式を指定する必要があります。

*C# の場合:*

[source,csharp]
----
this.ultraDataChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
----

*Visual Basic の場合:*

[source,vb]
----
Me.UltraDataChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg)
----

[[_Ref429040884]]

=== 関連コンテンツ

このトピックの追加情報については、以下のトピックも合わせてご参照ください。

[options="header", cols="a,a"]
|====
|トピック|目的

| _link:datachart-datachart.html[{DataChartName}]_ 
|このトピックでは、 _UltraDataChart_ コントロールの概要を説明します。

| _link:datachart-getting-started-with-datachart.html[データ チャートを使用した作業の開始]_ 
|このトピックでは、 _UltraDataChart_ を使用して作業を開始する方法に関する情報を提供します。

| link:datachart-series-requirements.html[シリーズ要件]
|このトピックでは、UltraDataChart で利用可能な散布シリーズに関する情報を提供します。

|====