////

|metadata|
{
    "name": "datachart-series",
    "controlName": ["{DataChartName}"],
    "tags": ["Charting","Data Binding","Getting Started"],
    "guid": "3d087135-84b0-4f6e-b3eb-afe7e962e406",  
    "buildFlags": [],
    "createdOn": "2014-06-05T19:39:00.6883931Z"
}
|metadata|
////

= チャート シリーズ

=== 目的
このトピックは、チャートの link:{DataChartLink}.series.html[シリーズ] シリーズ オブジェクトの概念を紹介し、シリーズのタイプ、シリーズ データの結合、およびシリーズの凡例についての手順を説明します。

link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ コントロールには、チャート プロット領域に link:{DataChartLink}.series.html[Series] オブジェクトを追加できる pick:[xaml,win-forms="link:{DataChartLinkBase}.{DataChartBase}{ApiProp}Series.html[Series]"]pick:[android="link:{DataChartLinkBase}.~addseries.html[AddSeries]"] {ApiMember} を提供します。異なるチャート シリーズを追加し、同じチャート コントロール内で複数のデータソースを表示し、複合チャートを作成できます。チャートに追加される各シリーズには、データ メンバーと軸タイプに適切なバインドが設定されている必要があります。

== データ バインディング

すべてのタイプの link:{DataChartLink}.series.html[シリーズ]は、実装するデータ ソースにバインドするための link:{DataChartLink}.Series~{ApiDataSource}.html[{ApiDataSource}] プロパティがあります。正しく描画するために 1 データ列または各データ項目のプロパティが必要なシリーズがあります。そのため、すべてのシリーズに共通のデータ マッピング プロパティはありません。代わりに、シリーズへのデータ マッピングのプロセスは、シリーズの Series の一意の MemberPath プロパティを使用することで達成されます。

== link:datachart-series-types.html[シリーズ タイプ] 

複数のシリーズがチャート コントロールに追加される場合、それぞれの連続するシリーズは、先頭から最後に向かって開始する前のシリーズの上にレイヤーされます。チャート シリーズの異なるタイプの複合チャートを簡単に作成できます。ただし、同時に使用できるチャートシリーズのタイプに制限があります。詳細については、 link:datachart-series-types.html[「シリーズ タイプ」]および link:datachart-multiple-series.html[「複数のシリーズ」]の適切なセクションを参照してください。

== link:datachart-series-requirements.html[シリーズ要件] 

チャート コントロールは、多数のさまざまなシリーズをサポートしますが、一部のシリーズでは満たす必要がある特定の要件があります。詳細については、 link:datachart-series-requirements.html[「シリーズ要件」]を参照してください。

ifdef::wpf,win-universal,xamarin,win-forms[]
== 凡例

シリーズの link:{DataChartLink}.series{ApiProp}legend.html[Legend] プロパティは、どの凡例項目がシリーズの link:{DataChartLink}.series{ApiProp}title.html[Title] および凡例バッジを示すかを決定します。
endif::wpf,win-universal,xamarin,win-forms[]

== 関連コンテンツ

このセクションは、{DataChartName} コントロールのシリーズでの作業に関するタスクベースの手順についての役立つ情報を提供します。

ifdef::sl,wpf[]
* link:datachart-creating-custom-series.html[カスタム シリーズの作成]

endif::sl,wpf[]

* link:datachart-multiple-series.html[複数シリーズの追加]

ifdef::sl,wpf,win-phone[]
* link:datachart-series-data-correlation.html[シリーズ データの相関]

endif::sl,wpf,win-phone[]

ifdef::sl,wpf,win-phone[]
* link:datachart-series-error-bars.html[シリーズ誤差範囲]

endif::sl,wpf,win-phone[]

* link:datachart-trend-lines.html[シリーズ トレンドライン]

ifdef::sl,wpf,win-rt[]
* link:datachart-series-highlighting.html[シリーズの強調表示]

endif::sl,wpf,win-rt[]

* link:datachart-series-requirements.html[シリーズ要件]
* link:datachart-series-types.html[シリーズ タイプ]