////

|metadata|
{
    "name": "datachart-working-with-multi-dimensional-data-(olap-data)-(xamdatachart)",
    "controlName": ["{DataChartName}"],
    "tags": ["Application Blocks","Charting","Drilldown","How Do I"],
    "guid": "33c32645-298d-4260-84eb-2fcf28872b60",  
    "buildFlags": ["SL","WPF"],
    "createdOn": "2014-06-05T19:39:00.5723466Z"
}
|metadata|
////

= チャートで多次元データの操作 (OLAP データ)

=== 概要

このセクションでは、多次元データ (Online Analytical Processing (OLAP) データ) と {DataChartName}™ コントロール使用の詳細を説明します。

=== トピック

_{DataChartName}_ の OLAP データの視覚化に関する詳しい情報については、次のトピックを参照してください。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:datachart-visualizing-multi-dimensional-data-(olap-data)-({DataChartName}).html[多次元データ (OLAP データ) を視覚化 ({DataChartName})]
|このトピックでは、{DataChartName} コントロールで多次元データ (OLAP データ) を表示する方法をコード例を示して説明します。

| link:datachart-customizing-series-when-used-with-multi-dimensional-data-(olap-data)-({DataChartName}).html[多次元データ (OLAP データ) と使用した時にシリーズをカスタマイズ ({DataChartName})]
|このトピックは、{DataChartName} コントロールで 1 つのチャートに複数シリーズ タイプを表示する、または多次元データ (OLAP データ) で作業する時に積層シリーズを使用する方法について説明します。

|====