////

|metadata|
{
    "name": "chart-data-sources-non-series-binding",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{95221DE6-9D88-4B4C-852D-1A20991EFB82}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= データ ソース（非 Series バインディング）

Chart のマニュアルは通常、チャート データを行と列で記述しますが、Chart コントロールでは DataTables への連結だけに限定していません。多くのアプリケーションでは、他のさまざまなデータソースが使用されています。Chart で使用するためだけに DataTable オブジェクトを作成することは理にかなっていません。

このため、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~datasource.html[UltraChart.DataSource]"]   pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[UltraChart.DataSource]"]  プロパティは、以下を含む広範なデータソース タイプをサポートします。

* link:chart-bind-a-treemap-chart-to-a-treemapseries-object.html[ツリーマップ チャートを TreeMapSeries オブジェクトへのバインディング]
* link:chart-binding-to-an-array.html[配列へのバインディング]
* link:chart-binding-to-classes-derived-from-collectionbase.html[CollectionBase から派生したクラスへのバインディング]
* link:chart-binding-to-a-dataset-dataview-or-datatable.html[DataSet、DataView、または DataTable へのバインディング]
* link:chart-binding-to-ibindinglist-or-ilist.html[IBindingList または IList へのバインディング]

ifdef::win-forms,win-forms-old[]
* link:chart-binding-to-windatasource.html[WinDataSource へのバインディング]

endif::win-forms,win-forms-old[]

* link:chart-binding-to-an-xml-file.html[XML ファイルへのバインディング]