////

|metadata|
{
    "name": "chart-specify-row-labels",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{866DF402-1BF7-417D-8C45-73218ECB701D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 行ラベルの指定

多くのグラフでデータセットの自動ラベリングをサポートしています。自動ラベリングは行に投影される最初の文字列の列に基づいています。別の列が希望のデータセットラベルを指定する場合、行のラベルの列を指定できます。このトピックでは、行ラベルとして、チャート タイプで指定するデフォルトの行ラベル以外を選択する方法を説明します。

このトピックは、データソースの指定列から行ラベルを取り込む方法を説明します。デフォルトでは、テーブル内の、文字列を含む最初の列から行ラベルを読み込みます。これを無効にするには、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  プロパティを True に設定します。これで、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  プロパティに、データソース内の行ラベルを含む列番号を設定できます。

以下のコードを入力し、行ラベルに使用する列を指定します。

*Visual Basic の場合：*

----
Private Sub Specify_Row_Labels_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraChart1.Data.UseRowLabelsColumn = True
	Me.UltraChart1.Data.RowLabelsColumn = 3
End Sub
----

*C# の場合：*

----
private void Specify_Row_Labels_Load(object sender, EventArgs e)
{
	this.ultraChart1.Data.UseRowLabelsColumn = true;
	this.ultraChart1.Data.RowLabelsColumn = 3;
}
----