////

|metadata|
{
    "name": "chart-change-icons-in-a-scatter-chart",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{3AB83E0B-C055-4BFB-A7D8-EDD642EC168E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 散布図内のアイコンの変更

このトピックでは、 link:chart-scatter-chart.html[散布図]内に表示するアイコンを変更する方法を説明します。グラフには表示できる 7 つの組み込みアイコンが含まれます。それらは、Plus、X、Triangle、Square、Circle、Diamond、および Upside Down Triangle です。表示するアイコンは、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  プロパティで指定します。

[start=1]
. コードの記述を開始する前にコード ビハインドに using/imports のディレクティブを配置します。そうすれば、メンバは完全に記述された名前を常に入力する必要がなくなります。

*Visual Basic の場合：*

----
Imports Infragistics.UltraChart.Shared.Styles
----

*C# の場合：*

----
using Infragistics.UltraChart.Shared.Styles;
----

[start=2]
. 散布図で使用するアイコンを菱形のアイコンに変更するには、以下のコードを入力します。

*Visual Basic の場合：*

----
Me.UltraChart1.ScatterChart.Icon = SymbolIcon.Diamond
----

*C# の場合：*

----
this.ultraChart1.ScatterChart.Icon = SymbolIcon.Diamond;
----

[start=3]
. 組み込みアイコンに加え、カスタム文字も表示できます。Icon プロパティを Character に設定し、チャート内に表示する文字を Character プロパティに指定します。これには、キーボード上にある文字、数字、または任意の記号を使用できます。

*Visual Basic の場合：*

----
Me.UltraChart1.ScatterChart.Icon = SymbolIcon.Character
Me.UltraChart1.ScatterChart.Character = "@"
----

*C# の場合：*

----
this.ultraChart1.ScatterChart.Icon = SymbolIcon.Character;
this.ultraChart1.ScatterChart.Character = '@';
----

== 関連トピック

link:chart-connect-scatter-chart-points-with-a-line.html[線による散布図の各点の結合] link:chart-axis-requirements-for-composite-charts.html[]