////

|metadata|
{
    "name": "chart-winchart-api-overview",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{012AA042-E1A0-43E0-98A3-4417ED6E1ACB}",  
    "buildFlags": ["win-forms","win-forms-old"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API 概要

このセクションは WinChart コントロールに関連する各名前空間をリストします。また、このコントロールでプログラミングをする時に使用するいくつかのキー クラスも示します。このページの名前空間とクラスは、ヘルプの「API 参照ガイド」に直接リンクしています。

[cols="a,a"]
|====
|*WinChart 名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart_namespace.html[Infragistics.Win.UltraWinChart]"]
|*キー クラス:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart.html[UltraChart]"]

|*Core 名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core_namespace.html[Infragistics.UltraChart.Core]"]
|*キー クラスとインタフェース:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.chartcore.html[ChartCore] 

endif::win-forms[] 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.scenegraph.html[SceneGraph] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.iadvanceaxis.html[IAdvanceAxis]"]

|*レイヤ名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.layers_namespace.html[Infragistics.UltraChart.Core.Layers]"]
|*キー インタフェース:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.layers.ilayer.html[ILayer interface]"]

|*プリミティブ名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives_namespace.html[Infragistics.UltraChart.Core.Primitives]"]
|*キー クラス:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitive]"]

|*Util 名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util_namespace.html[Infragistics.UltraChart.Core.Util]"]
|*キー クラス:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util.labelformatter.html[LabelFormatter] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util.platform.html[Platform]"]

|*データ名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data_namespace.html[Infragistics.UltraChart.Data]"]
|*キー クラス:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.demotable.html[DemoTable] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.ganttdatasource.html[GanttDataSource]"]

|*リソース名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources_namespace.html[Infragistics.UltraChart.Resources]"]
|*キー インタフェース:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.ichartcomponent.html[IChartComponent] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.irenderlabel.html[IRenderLabel]"]

|*外観名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance_namespace.html[Infragistics.UltraChart.Resources.Appearance]"]
|*キー クラス:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.annotation.html[Annotation] 

endif::win-forms[] 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.effect.html[Effect] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]

|*イベント名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events_namespace.html[Infragistics.UltraChart.Shared.Events]"]
|*キー クラス:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdataeventargs.html[ChartDataEventArgs] 

endif::win-forms[] 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdatainvalideventargs.html[ChartDataInvalidEventArgs] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdrawitemeventargs.html[ChartDrawItemEventArgs]"]

|*スタイル名前空間:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles_namespace.html[Infragistics.UltraChart.Shared.Styles]"]
|*キー クラスと列挙体:* 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.labelstyle.html[LabelStyle] 

endif::win-forms[] 

ifdef::win-forms[] 

link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.linestyle.html[LineStyle] 

endif::win-forms[] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.charttype.html[ChartType 列挙体]"]

|====