////

|metadata|
{
    "name": "chart-charts-event-model",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{AB604742-1025-4C5E-AE6A-8F3C6BA6EA27}",  
    "buildFlags": [],
    "createdOn": "2008-05-12T10:20:16Z"
}
|metadata|
////

= チャートのイベント モデル

Chart コントロールは、ほとんどのビジネス問題を解決する任意の種類のプログラミング ロジックを達成するために処理できる多くのイベントを提供します。Chart がどのようなイベントを提供すべきかを知ることによって、プログラミングで管理を遙かにシンプルかつ簡単にすることができます。

これらのイベントを処理するためには、Chart のオブジェクト モデルの基本を理解する必要があります。多くの Chart オブジェクトは、イベント ハンドラーでアクセスできるイベント引数によって提供されます。使用可能なイベントが豊富にあるため、任意の種類の複雑なビジネスロジックをある方法または別の方法で実装できない訳はありません。

このセクションでは、多くのアプリケーションに装備されている基本的な機能を実現するために使用できるいくつかの有用なイベントについて学習します。

以下をクリックして Chart のイベントでもっともよく使用されるイベントのいくつかについて学習します。

* link:chart-chartdrawitem-event.html[ChartDrawItem イベント]
* link:chart-event-model-click-events.html[Click イベント]
* link:chart-fillscenegraph-event.html[FillSceneGraph イベント]
* link:chart-access-axis-inside-fillscenegraph-event-of-a-composite-chart.html[合成チャートの FillSceneGraphEvent イベント内の軸にアクセス]
* link:chart-access-axis-inside-fillscenegraph-event-of-a-non-composite-chart.html[非合成チャートの FillSceneGraphEvent イベント内の軸にアクセス]
* link:chart-modify-scene-graph-using-fillscenegraph-event.html[FillSceneGraph イベントを使用してシーン グラフを変更]

ifdef::win-forms-old,win-forms[]
* link:chart-determine-which-axis-is-being-scrolled-or-scaled.html[スクロールまたはスケールする軸を決定する]

endif::win-forms-old,win-forms[]

ifdef::aspnet-old,asp-net[]
* link:chart-client-side-events.html[クライアント側イベント]

endif::aspnet-old,asp-net[]