////

|metadata|
{
    "name": "chart-series-collection",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{B15FB09B-5B62-4848-BE13-506E97102FF2}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Series コレクション

pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  クラスは、Chart コントロールのデータソースとして提供されます。このデータソースは、デザインタイムおよびランタイムで簡単にアクセスできます。Series コレクションは、強力にタイプ化され、さまざまなグラフの種類の要件に適合するさまざまなデータ構造を表す 1 つまたは複数の Series オブジェクトが含まれています。

合成  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~charttype.html[ChartType]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~charttype.html[ChartType]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~charttype.html[ChartType]"]  は、データソースとして SeriesCollection だけを使用します。他のチャート タイプについては、Data. pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~datasource.html[DataSource]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[DataSource]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[DataSource]"]  プロパティが設定されていない場合にシリーズ コレクションが使用されます。

各シリーズには、「ポイント」と呼ばれる DataPoints のコレクションがあります。このコレクションは、デザインタイムまたはランタイムで格納または変更できます。これは "Data" と呼ばれるそれ自体が DataSource プロパティを含むプロパティを持ちます。このプロパティは DataTable に設定できます。さらに、どの列をデータの取得に使用するかを指定するプロパティがあります。これらの Column プロパティはタイプごとに異なるため、一覧については、使用する Series のタイプの API リファレンス ガイドを参照してください。

== 関連トピック

link:chart-creating-a-composite-chart-in-code-part-1-of-2.html[コードで合成チャートを作成（1/2）]

link:chart-requirements-for-series-binding.html[Ｓｅｒｉｅｓ バインディングの要件]

link:chart-axis-requirements-for-composite-charts.html[合成チャートの軸要件]