////

|metadata|
{
    "name": "chart-exporting-to-pdf",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{6EC7E9F9-E4FD-4D8F-B650-81A7D3C64997}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= PDF にエクスポート

この機能によって、数行のコードだけで Portable Document Format（PDF）ファイルまたは XML Paper Specification（XPS）ファイルのいずれかにチャートをエクスポートすることができます。

チャートの PDF へのエクスポートは、Document Engine と連動して機能します。Document Engine に関する詳細は、 pick:[win-forms,win-forms-old="link:waw-infragistics-document-engine.html[Infragistics Document Engine]"]  pick:[asp-net,aspnet-old="link:waw-infragistics-document-engine.html[Infragistics Document Engine]"]  を参照してください。

System.Drawing.Graphics オブジェクトを受け付けるパブリック メソッド  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  が公開されています。

ピクセルの幅と高さだけでなく System.Drawing.Graphics オブジェクトを受け付ける RenderPdfFriendlyGraphics メソッドのオーバーロードも使用できます。チャートの寸法が大きすぎて PDF ドキュメントのキャンバスに収まらない場合には、描画された画像は指定されたサイズに基づいてチャート サイズ比まで縮小されます。

Canvas 要素で Report を作成し、次にグラフィックス オブジェクトをチャートのレンダラに渡すために Canvas 要素で CreateGraphics メソッドを呼び出す必要があります。

Report を手動で作成する必要があります。チャートには Infragistics.Documents アセンブリが自動的に含まれないからです。このアセンブリは PDF ファイルと連動するために必要です。

このアセンブリはチャートの一部ではありませんが、PDF にエクスポート機能を使用していない場合でさえ、それ以外の方法で常に余分のアセンブリを含めています。

== 関連トピック

link:chart-export-to-pdf.html[PDF にエクスポート]