////

|metadata|
{
    "name": "chart-connect-scatter-chart-points-with-a-line",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{920E88CF-861B-44F9-B684-70FA8A4BA44A}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 線による散布図の各点の結合

このトピックでは、 link:chart-scatter-chart.html[散布図]内の各点を線で結ぶ方法を説明します。線で結ぶと、グラフ上のデータ点間の差をより簡単に視覚化できます。

散布図上の点を結ぶ線を作成するには、散布図の  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  プロパティを True に変更するだけです。

*Visual Basic の場合：*

----
Me.UltraChart1.ScatterChart.ConnectWithLines = True
----

*C# の場合：*

----
this.ultraChart1.ScatterChart.ConnectWithLines = true;
----

このコードは、散布図内の各点を線で結びます。線は、最初の点から順番に結んでいき、最後の要素で終了します。このプロパティを True に設定すると結合線が表示され、False に設定すると線が表示されなくなります。

== 関連トピック

link:chart-change-icons-in-a-scatter-chart.html[散布図内のアイコンの変更]