////

|metadata|
{
    "name": "chart-customize-chart-legends",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{4DD3A232-065E-4FB1-A337-D388D228B654}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= グラフ凡例をカスタマイズ

このトピックでは、Chart コントロール内の凡例をカスタマイズする方法を簡単に説明します。

グラフの凡例の位置を、グラフの上部、下部、右側、左側のいずれかに設定できます。凡例のサイズ設定や余分な空白の削除を行うには、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~margins.html[Margins]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~margins.html[Margins]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~margins.html[Margins]"]  および  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~spanpercentage.html[SpanPercentage]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~spanpercentage.html[SpanPercentage]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~spanpercentage.html[SpanPercentage]"]  プロパティを組み合わせて使用します。たとえば、4 項目しか含まない凡例をグラフの右側に表示する場合、上部マージンと下部マージンを大きくして凡例の高さを小さくできます。この場合、SpanPercentage で凡例の幅を小さくすることも可能です。

[start=1]
. コードの記述を開始する前にコード ビハインドに using/imports のディレクティブを配置します。そうすれば、メンバは完全に記述された名前を常に入力する必要がなくなります。

*Visual Basic の場合：*

----
Imports Infragistics.UltraChart.Shared.Styles
----

*C# の場合：*

----
using Infragistics.UltraChart.Shared.Styles;
----

[start=2]
. 以下のコードは、マージンおよび SpanPercentage プロパティを使用して凡例の位置設定やサイズ調整を行う方法を示します。

*Visual Basic の場合：*

----
Me.UltraChart1.Legend.Visible = True
Me.UltraChart1.Legend.Location = LegendLocation.Right
Me.UltraChart1.Legend.Margins.Left = 5
Me.UltraChart1.Legend.Margins.Right = 10
Me.UltraChart1.Legend.Margins.Top = 15
Me.UltraChart1.Legend.Margins.Bottom = 90
Me.UltraChart1.Legend.SpanPercentage = 15
----

*C# の場合：*

----
this.ultraChart1.Legend.Visible = true;
this.UltraChart1.Legend.Location = Infragistics.UltraChart.Shared.Styles.LegendLocation.Right;
this.UltraChart1.Legend.Margins.Left = 5;
this.UltraChart1.Legend.Margins.Right = 10;
this.UltraChart1.Legend.Margins.Top = 15;
this.UltraChart1.Legend.Margins.Bottom = 90;
this.UltraChart1.Legend.SpanPercentage = 15;
----

[start=3]
. 凡例の外観をカスタマイズすることもできます。色を変更する場合は、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~backgroundcolor.html[BackgroundColor]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~backgroundcolor.html[BackgroundColor]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~backgroundcolor.html[BackgroundColor]"] 、および  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~fontcolor.html[FontColor]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~fontcolor.html[FontColor]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~fontcolor.html[FontColor]"]  プロパティを使用します。 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderthickness.html[BorderThickness]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderthickness.html[BorderThickness]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderthickness.html[BorderThickness]"] 、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderstyle.html[BorderStyle]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderstyle.html[BorderStyle]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~borderstyle.html[BorderStyle]"] 、および  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~alphalevel.html[AlphaLevel]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~alphalevel.html[AlphaLevel]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.legendappearance~alphalevel.html[AlphaLevel]"]  プロパティは、外観を変更するために使用することもできます。以下のコードは、凡例にさまざまな書式属性を設定する方法を示します。

*Visual Basic の場合：*

----
Me.UltraChart1.Legend.BackgroundColor = System.Drawing.Color.Yellow
Me.UltraChart1.Legend.FontColor = System.Drawing.Color.Blue
Me.UltraChart1.Legend.BorderColor = System.Drawing.Color.Red
Me.UltraChart1.Legend.BorderStyle = LineDrawStyle.Dash
Me.UltraChart1.Legend.BorderThickness = 3
Me.UltraChart1.Legend.AlphaLevel = 25
----

*C# の場合：*

----
this.UltraChart1.Legend.BackgroundColor = System.Drawing.Color.Yellow;
this.UltraChart1.Legend.FontColor = System.Drawing.Color.Blue;
this.UltraChart1.Legend.BorderColor = System.Drawing.Color.Red;
this.UltraChart1.Legend.BorderStyle = LineDrawStyle.Dash;
this.UltraChart1.Legend.BorderThickness = 3;
this.UltraChart1.Legend.AlphaLevel = 25;
----