////

|metadata|
{
    "name": "chart-render-charts-using-the-paint-element",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{8811E214-DACC-4A8E-8122-2856420CC716}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 描画エレメントを使用してグラフを描画

このセクションは、グラフィカル チャート要素（ pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"] ）およびチャート外観で公開された  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"] （PE プロパティ）のアプリケーションについて説明します。描画要素を使用すると、開発者はこれらのオブジェクトの描画に対して高度な制御が可能になります。描画要素には、チャートの各要素を塗りつぶす方法や、これらの要素の輪郭線の描画方法を制御するプロパティが含まれています。

各タスクの実行方法については以下のリンクをクリックしてください。

* link:chart-apply-a-gradient-effect-to-a-primitive.html[プリミティブにグラデーション効果を適用]
* link:chart-apply-a-hatch-style-to-a-primitive.html[プリミティブハッチ スタイルを適用]
* link:chart-apply-a-texture-effect-to-a-primitive.html[プリミティブにテクスチャ効果を適用]
* link:chart-apply-an-image-to-a-chart-primitive.html[チャート プリミティブに画像を適用]
* link:chart-customize-the-appearance-of-a-charts-background.html[チャートの背景の外観をカスタマイズ]
* link:chart-set-the-opacity-of-a-gradient-effect.html[グラデーションの不透明度を設定]
* link:chart-use-a-custom-brush-in-a-paintelement.html[PaintElement でカスタム ブラシを使用]
* link:chart-use-the-paintelements-elementtype-property.html[PaintElement の ElementType プロパティを使用]
* link:chart-use-the-paintelements-fill-stroke-and-strokewidth-properties.html[PaintElement の Fill、Stroke、および StrokeWidth プロパティを使用]