////

|metadata|
{
    "name": "chart-optimize-the-rendering-speed",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{391E70B1-4B0A-4CEC-9D48-8B8D95630B98}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 描画速度の最適化

Chart 要素は通常、高速でグラフを描画します。ただし、膨大な数のデータ点をプロットする場合、パフォーマンスを最適化するために  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~tooltips.html[Tooltips]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.webtooltipappearance.html[Tooltips]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.webtooltipappearance.html[Tooltips]"]  オブジェクトの  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.wintooltipappearance~display.html[Display]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.webtooltipappearance~display.html[Display]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.webtooltipappearance~display.html[Display]"]  プロパティを正しく設定しなければならない場合があります。また、イメージ マップを生成しない設定にすると、要素の描画速度が改善されます。

以下のコード例は、ツールチップを無効にするために Display プロパティを設定する方法を示しています。

*Visual Basic の場合：*

----
Imports Infragistics.UltraChart.Shared.Styles
...
Imports Infragistics.UltraChart.Shared.Styles
Private Sub Optimize_the_Rendering_Speed_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraChart1.Tooltips.Display = TooltipDisplay.Never
End Sub
----

*C# の場合：*

----
using Infragistics.UltraChart.Shared.Styles;
...
using Infragistics.UltraChart.Shared.Styles;
private void Optimize_the_Rendering_Speed_Load(object sender, System.EventArgs e)
{
	this.ultraChart1.Tooltips.Display = TooltipDisplay.Never;
}
----