////

|metadata|
{
    "name": "chart-map-a-leaf-nodes-color-to-a-specific-column-in-a-data-table",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{E6CA2267-9871-47AB-B4EC-5D03C74C4B78}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= データ テーブルで特定の列にリーフ ノードの色を割り当てる

このトピックでは、データ テーブルで特定の列にリーフ ノードの色をマップする方法を説明します。 pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[ColorValueIndex]"]  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[ColorValueIndex]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[ColorValueIndex]"]  プロパティは数値を含むデータ列のインデックスです。ColorValueIndex を設定しない場合には、データ テーブルの最初の数値列にデフォルト設定されます。ColorValueIndex プロパティはゼロから始まるインデックスです。

たとえば、以下のデータ テーブルがある場合:

[cols="a,a,a,a"]
|====
|*Category*
|*Name*
|*Unit Price*
|*Yearly Sales*

|Fruit
|Apples
|1
|20

|Diary
|Cheese
|2
|25

|Meat
|Steak
|3
|30

|====

ColorValueIndex プロパティを 3 に設定すると、Yearly Sales 列を使用してリーフ ノードの色を生成します。ColorValueIndex プロパティを設定しない場合には、データ テーブルの最初の数値列にデフォルト設定されます。この例では Unit Price 列です。

リーフ ノードの色は、ColorModel.ColorBegin および ColorModel.ColorEnd プロパティの設定に基づいてスケールされます。

ColorModel.ColorBegin プロパティが Blue に設定され、ColorModel.ColorEnd プロパティが Red に設定されており、データ列が 0 から 10 の値を含む場合、以下のようになります:

* リーフ ノードの値が 0 であると青になります。
* リーフ ノードの値が 5 であると紫になります（青と赤の中間）。
* リーフ ノードの値が 10 であると赤になります。

以下の例のコードは ColorValueIndex プロパティを設定する方法を示します。

*Visual Basic の場合：*

----
Me.ultraChart1.ColorModel.ColorBegin = System.Drawing.Color.Blue
Me.ultraChart1.ColorModel.ColorEnd = System.Drawing.Color.Red
Me.ultraChart1.TreeMapChart.ColorValueIndex = 3
----

*C# の場合：*

----
this.ultraChart1.ColorModel.ColorBegin = System.Drawing.Color.Blue;
this.ultraChart1.ColorModel.ColorEnd = System.Drawing.Color.Red;       
this.ultraChart1.TreeMapChart.ColorValueIndex = 3;
----

リーフ ノードの色がデータ列の値に基づくようにしたくない場合には、リーフ ノードのカスタム PaintElement を設定することも可能です。

以下の例のコードは、リーフ ノードのカスタム PaintElement を設定する方法を示します。

*Visual Basic の場合：*

----
Me.ultraChart1.TreeMapChart.StaticLeafPE = New Infragistics.UltraChart.Resources.Appearance.PaintElement
(System.Drawing.Color.Silver, 
System.Drawing.Color.Gold, 
Infragistics.UltraChart.Shared.Styles.GradientStyle.HorizontalBump)
Me.ultraChart1.TreeMapChart.UseStaticLeafPE = True;
----

*C# の場合：*

----
this.ultraChart1.TreeMapChart.StaticLeafPE = 
   new Infragistics.UltraChart.Resources.Appearance.PaintElement
   (System.Drawing.Color.Silver, System.Drawing.Color.Gold, 
  Infragistics.UltraChart.Shared.Styles.GradientStyle.HorizontalBump);
this.ultraChart1.TreeMapChart.UseStaticLeafPE = true;
----

== 関連トピック

link:chart-set-a-treemap-charts-color-based-on-hierarchical-level.html[階層レベルに基づいてツリーマップ グラフの色を設定]

link:chart-set-a-leaf-nodes-color-using-a-treemapseries-object.html[TreeMapSeries オブジェクトを使用してリーフ ノードの色を設定]