////

|metadata|
{
    "name": "chart-customize-chart-tooltips",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{E6506698-2409-4F87-ACA2-7BCEBE0394AE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= チャートのツールチップをカスタマイズ

このトピックでは、Chart コントロール内で表示するツールチップをカスタマイズする方法を説明します。

[start=1]
. コードの記述を開始する前にコード ビハインドに using/imports のディレクティブを配置します。そうすれば、メンバは完全に記述された名前を常に入力する必要がなくなります。

*Visual Basic の場合：*

----
Imports Infragistics.UltraChart.Shared.Styles
----

*C# の場合：*

----
using Infragistics.UltraChart.Shared.Styles;
----

[start=2]
. マウスでチャート データをポイントまたはクリックしたときに、ツールチップを表示させたり、あるいはまったく表示させないように設定できます。以下のコードは、チャート内のデータをクリックした場合に表示するツールチップを設定します。

*Visual Basic の場合：*

----
Me.UltraChart1.Tooltips.Display = TooltipDisplay.MouseClick
----

*C# の場合：*

----
this.ultraChart1.Tooltips.Display = TooltipDisplay.MouseClick;
----

[start=3]
. データ点をマウスでポイントしたときに、対応する文字列を表示するように、ツールチップを設定できます。この値には、データ値、軸ラベルとデータ値、あるいは行（列）番号とデータ値のいずれかを取ることができます。

*Visual Basic の場合：*

----
Me.UltraChart1.Tooltips.Format = TooltipStyle.LabelPlusDataValue
----

*C# の場合：*

----
this.ultraChart1.Tooltips.Format = TooltipStyle.LabelPlusDataValue;
----

[start=4]
. ツールチップはカスタム文字列も表示できます。 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.wintooltipappearance~format.html[Format]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.axisserieslabelappearance~format.html[Format]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.axisserieslabelappearance~format.html[Format]"]  プロパティを「カスタム」に、 pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.wintooltipappearance~formatstring.html[FormatString]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.axisserieslabelappearance~formatstring.html[FormatString]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.axisserieslabelappearance~formatstring.html[FormatString]"]  プロパティを表示される文字列に設定することで、これが可能になります。

*Visual Basic の場合：*

----
Me.UltraChart1.Tooltips.Format = TooltipStyle.Custom
Me.UltraChart1.Tooltips.FormatString = "tooltip"
----

*C# の場合：*

----
this.ultraChart1.Tooltips.Format = TooltipStyle.Custom;
this.ultraChart1.Tooltips.FormatString = "tooltip";
----

[start=5]
. また、ツールチップの外観も制御できます。以下のコードは、ツールチップの背景、テキスト、および枠の書式属性を設定します。

*Visual Basic の場合：*

----
Me.UltraChart1.Tooltips.BackColor = System.Drawing.Color.Yellow
Me.UltraChart1.Tooltips.FontColor = System.Drawing.Color.Blue
Me.UltraChart1.Tooltips.BorderColor = System.Drawing.Color.Red
Me.UltraChart1.Tooltips.BorderThickness = 3
----

*C# の場合：*

----
this.ultraChart1.Tooltips.BackColor = Color.Yellow;
this.ultraChart1.Tooltips.FontColor = Color.Blue;
this.ultraChart1.Tooltips.BorderColor = Color.Red;
this.ultraChart1.Tooltips.BorderThickness = 3;
----