////

|metadata|
{
    "name": "chart-save-a-chart-image",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{D4E296FD-AD41-453C-A615-0BAA7BF2E464}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= チャート画像の保存

このトピックでは、要素の  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~saveto.html[SaveTo]"]  pick:[asp-net="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~saveto.html[SaveTo]"]  pick:[aspnet-old="link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~saveto.html[SaveTo]"]  メソッドを使用して、グラフの画像を現在の状態で保存する方法について説明します。

[start=1]
. SaveTo メソッドは、グラフの画像をファイルまたはストリームに保存するために使用できます。ファイルに保存するには、パスと画像の形式を指定する必要があります。以下のコード行は、グラフを JPEG 画像ファイルに保存します。

*Visual Basic の場合：*

----
Me.UltraChart1.SaveTo("chart.jpg", System.Drawing.Imaging.ImageFormat.Jpeg)
----

*C# の場合：*

----
this.UltraChart1.SaveTo("chart.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg);
----

[start=2]
. グラフのバイナリ画像データもストリームに保存することができます。この場合、ストリームと画像の形式を指定する必要があります。

*Visual Basic の場合：*

----
Me.UltraChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg)
----

*C# の場合：*

----
this.UltraChart1.SaveTo(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
----