////
|metadata|
{
    "name": "piechart-selection",
    "controlName": ["{PieChartName}"],
    "tags": ["Charting","Data Presentation","How Do I"],
    "guid": "",
    "buildFlags": ["SL","WPF","win-phone","WINFORMS","ANDROID","XAMARIN"],
    "createdOn": "2014-06-05T19:53:12.0788999Z"
}
|metadata|
////

= {DataPieChartName}

The link:{DataPieChartLink}.{DataPieChartName}.html[{DataPieChartName}] is a specialized control that renders a pie chart, consisting of a circular area divided into sections. Each section has arc length proportional to its underlying data value.

The {DataPieChartName} control is used for representing categorical data. It is most effective when there are only a few categories, and when each category makes up a relatively large percentage of the data as a whole.

ifdef::wpf[]
The {DataPieChartName} control exists within the Infragistics.WPF.Charts NuGet package.
endif::wpf[]

ifdef::win-forms[]
The {DataPieChartName} control exists within the Infragistics.WinForms.Charts NuGet package.
endif::win-forms[]

== link:data-pie-chart-getting-started.html[Getting Started with {DataPieChartName}]

In order to get you up and running as quickly as possible with the {DataPieChartName} control, we've provided you with information on how to get started using the control.

== link:data-pie-chart-configuration.html[Configuring {DataPieChartName}]

This section contains information on the key features and functionalities provided by the {DataPieChartName} control.


== link:data-pie-chart-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the {DataPieChartName} control.