////
|metadata|
{
    "name": "sparkline-sparkline-data-binding",
    "controlName": ["{SparklineName}"],
    "tags": ["Charting","Data Binding"],
    "guid": "3b2b2088-98d2-46fc-84a1-86397c679f73",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.2363484Z"
}
|metadata|
////

= {SparklineName} Data Binding



=== Purpose

This topic explains, with code examples, how to bind the link:{ApiPlatform}{SparklineAssembly}.html[{SparklineName}]™ control to data.

=== Required background

The following table lists the topics required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:sparkline-sparkline-overview.html[{SparklineName} Overview]
|This topic provides an overview of the _{SparklineName}_ control, its benefits, and the supported chart types.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref317187002,Data Binding – Conceptual Overview>>

** <<_Ref317187009,Overview>>
** <<_Ref317187012,Property settings>>

* <<_Ref317187018,Data Binding – Code Examples>>
* <<_Ref317187132,Related Content>>

[[_Ref317187002]]
== Data Binding – Conceptual Overview

[[_Ref317187009]]

=== Overview

The  _{SparklineName}_   control requires one-dimensional data. The data set must contain at least two  _numeric_  fields. If these data type requirements are not met  _{SparklineName}_   renders a blank chart (no error is returned). The text in the data source fields can be used to display the first and the last label on the X axis.

As a minimum, _{SparklineName}_   requires the
ifdef::sl,wpf,win-phone,win-universal,xamarin[]
link:{SparklineLink}.{SparklineName}~itemssource.html[ItemsSource] 
endif::sl,wpf,win-phone,win-universal,xamarin[]
ifdef::win-forms[] 
link:{SparklineLink}.{SparklineName}~datasource.html[DataSource] 
endif::win-forms[]
property which is used to bind the control to an instance of the data collection and the link:{SparklineLink}.{SparklineName}~valuememberpath.html[ValueMemberPath] property to identify what data to should be displayed.

[[_Ref317187012]]

=== Property settings

The following table lists the data binding property settings.

[options="header", cols="a,a"]
|====
|Property name|Property setting

ifdef::sl,wpf,win-phone,win-universal,xamarin[]
| _ItemsSource_ 
| _{Binding Source={StaticResource resource key name}}_ 
endif::sl,wpf,win-phone,win-universal,xamarin[]
ifdef::win-forms[] 
| _DataSource_ 
| _Collection of data_
endif::win-forms[] 

| _ValueMemberPath_ 
| _field name_ 

|====

[[_Ref317187018]]

== Code Example: Data Binding

=== Description

The following code demonstrates the data binding.

=== Explanation
ifdef::sl,wpf,win-phone,win-universal,xamarin[]
*In XAML:*

[source,xaml]
----
<UserControl
    xmlns:igSparkline="http://schemas.infragistics.com/xaml"
    xmlns:local="clr-namespace:SparklineDemo">
    <UserControl.Resources>
        <local:TestData x:Key="testdata"/> 
    </UserControl.Resources>
     <igSparkline:{SparklineName} 
          Name="{SparklineName}1"
         ItemsSource="{Binding Source={StaticResource testdata}}"
         ValueMemberPath="Value"/>
----
endif::sl,wpf,win-phone,win-universal,xamarin[]
*In C#:*

[source,csharp]
ifdef::sl,wpf,win-phone,win-universal,xamarin[] 
----
this.{SparklineName}1.ItemsSource = new TestData();
----
endif::sl,wpf,win-phone,win-universal,xamarin[] 
ifdef::win-forms[] 
----
this.{SparklineName}1.DataSource = new TestData();
this.{SparklineName}1.ValueMemberPath = "Value";
----
endif::win-forms[] 


ifdef::sl,wpf,win-phone,win-universal,win-forms[] 
*In Visual Basic:*

[source,vb]
ifdef::sl,wpf,win-phone,win-universal[] 
----
Me.{SparklineName}1.ItemsSource = New TestData()
----
endif::sl,wpf,win-phone,win-universal[] 
ifdef::win-forms[] 
----
Me.{SparklineName}1.DataSource = New TestData()
Me.{SparklineName}1.ValueMemberPath = "Value"
----
endif::win-forms[] 
endif::sl,wpf,win-phone,win-universal,win-forms[]

*In C#:*

[source,csharp]
----
public class TestData : ObservableCollection<TestDataItem>
    {
        public TestData()
        {
           Add(new TestDataItem { Label = "Label1", Value = 1 });
           Add(new TestDataItem { Label = "Label2", Value = 2 });
           Add(new TestDataItem { Label = "Label3", Value = 3 });
           Add(new TestDataItem { Label = "Label4", Value = -4 });
           Add(new TestDataItem { Label = "Label5", Value = 5 });
           Add(new TestDataItem { Label = "Label6", Value = -6 });
           Add(new TestDataItem { Label = "Label7", Value = 7 });
           Add(new TestDataItem { Label = "Label8", Value = 8 });
           Add(new TestDataItem { Label = "Label9", Value = 9 });
        }
    }
public class TestDataItem : INotifyPropertyChanged
    {
        private string _label;
        public string Label
        {
            get { return _label; }
            set { _label = value; RaisePropertyChanged("Label"); }
        }
        private double? _value;
        public double? Value
        {
            get { return _value; }
            set { _value = value; RaisePropertyChanged("Value"); }
        }
        private void RaisePropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new   PropertyChangedEventArgs(propertyName));
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;
    }
----
ifdef::sl,wpf,win-phone,win-universal,win-forms[] 



*In Visual Basic:*

[source,vb]
----
Public Class TestData
   Inherits ObservableCollection(Of TestDataItem)
      Public Sub New()
      Add(New TestDataItem() With {.Label = "Label1", .Value = 1})
      Add(New TestDataItem() With {.Label = "Label2", .Value = 2})
      Add(New TestDataItem() With {.Label = "Label3", .Value = 3})
      Add(New TestDataItem() With {.Label = "Label4", .Value = -4})
      Add(New TestDataItem() With {.Label = "Label5", .Value = 5})
      Add(New TestDataItem() With {.Label = "Label6", .Value = -6})
      Add(New TestDataItem() With {.Label = "Label7", .Value = 7})
      Add(New TestDataItem() With {.Label = "Label8", .Value = 8})
      Add(New TestDataItem() With {.Label = "Label9", .Value = 9})
   End Sub
End Class
Public Class TestDataItem
      Implements INotifyPropertyChanged
      Private _label As String
      Public Property Label() As String
            Get
                  Return _label
            End Get
            Set
                  _label = value
                  RaisePropertyChanged("Label")
            End Set
      End Property
      Private _value As System.Nullable(Of Double)
      Public Property Value() As System.Nullable(Of Double)
            Get
                  Return _value
            End Get
            Set
                  _value = value
                  RaisePropertyChanged("Value")
            End Set
      End Property
      Private Sub RaisePropertyChanged(propertyName As String)
            RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
      End Sub
      Public Event PropertyChanged As PropertyChangedEventHandler
End Class
----
endif::sl,wpf,win-phone,win-universal,win-forms[] 

[[_Ref317187132]]
== Related Content



The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:sparkline-sparkline-overview.html[{SparklineName} Overview]
|This topic provides an overview of the _{SparklineName}_ control, its benefits, and the supported chart types.

| link:sparkline-configuring-sparkline.html[Configuring {SparklineName}]
|This topic provides an overview of the possible ways to configure the _{SparklineName}_ control. Links to the detailed configurations (available in separate topics) are provided as well.

| link:sparkline-sparkline-property-reference.html[{SparklineName} Property Reference]
|This topic explains the featured properties of the _{SparklineName}_ control.

|====