////
|metadata|
{
    "name": "xambarcode-about-xambarcode",
    "controlName": ["{BarcodesName}"],
    "tags": [],
    "guid": "0a470afd-160c-4ac5-9690-e92335c26e78",
    "buildFlags": [],
    "createdOn": "2015-09-23T20:38:46.2797104Z"
}
|metadata|
////

= {BarcodesName} について

シッピング コンテナーから医療記録、さらには食料品の缶詰めまで、バーコードは、物的資産にデータ付けて識別するユニバーサルな方法になりました。産業界では、その業界に特有の機能を提供するバーコードの作成など、バーコード技術の基準を設けています。バーコード コントロールは、さまざまな幅広く採用されたバーコード標準に一致するスクリーン バーコード画像の描画ができるコントロールのセットをユーザーに提供することにより、バーコード書式でデータをアプリケーションに簡単に組み込むことができます。コントロールは、ほとんどの手順とバーコードを作成する手間を省くことができ、アプリケーションに簡単にバーコードを埋め込むことができます。

コントロールの {BarcodesName} シリーズは、以下のバーコード記号のサポートを提供しますpick:[wpf,android,win-forms="（各バーコードは個別のコントロールであることに注意）"]。

* link:xambarcode-configuring-qr-code.html[QR コードの構成]
ifdef::wpf,win-forms,android[]
* link:xambarcode-configuring-code128.html[コード 128 の構成]
endif::wpf,win-forms,android[]
ifdef::wpf,win-forms[]
* link:xambarcode-xamcode39barcode.html[コード 39]
* link:xambarcode-xameanupcbarcode.html[Ean/Upc]
* link:xambarcode-xaminterleaved2of5barcode.html[Interleaved 2 Of 5]
* link:xambarcode-xamgs1databarbarcode.html[GS1 DataBar]
* link:xambarcode-xamintelligentmailbarcode.html[Intelligent Mail]
* link:xambarcode-xamroyalmailbarcode.html[Royal Mail]
* link:xambarcode-xampdf417barcode.html[PDF 417]
* link:xambarcode-xammaxicodebarcode.html[Maxi Code]
endif::wpf,win-forms[]

== 関連トピック

* link:xambarcode-barcode-symbologies.html[バーコード記号]