= データ凡例

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] は `Legend` のように機能するコンポーネントですが、シリーズの値の表示や、シリーズの行と値の列のフィルタリング、値のスタイルと書式を設定するための多くの構成プロパティを提供します。この凡例は、link:{FinancialChartLink}.{FinancialChartName}.html[{FinancialChartName}] のプロット領域内でマウスを移動すると更新され、ユーザーのマウス ポインターがプロット領域を離れたときに最後にホバーされたポイントを記憶する永続的な状態になります。このコンテンツは、3 種類の行と 4 種類の列のセットを使用して表示されます。


== データ凡例の行

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] の行には、ヘッダー行、シリーズ行、および集計行が含まれます。

ヘッダー行には、ホバーされたポイントの軸ラベルが表示され、link:{DataChartLink}.{DataLegendName}{ApiProp}HeaderText.html[HeaderText] プロパティを使用して変更できます。

シリーズ行は、実際には、チャートにプロットされた各シリーズに対応する行のセットにすることができます。これらの行には、凡例バッジ、シリーズ タイトル、シリーズの実際の値 / 省略値、および指定されている場合は省略記号と単位が表示されます。

最後に、すべてのシリーズ値の合計を表示する集計行があります。デフォルトの集計タイトルは、凡例の link:{DataChartLink}.{DataLegendName}{ApiProp}SummaryTitleText.html[SummaryTitleText] プロパティを使用して変更できます。また、link:{DataChartLink}.{DataLegendName}{ApiProp}SummaryType.html[SummaryType] プロパティを使用して、シリーズ値の合計、最小、最大、または平均を集計行に表示するかどうかをカスタマイズできます。

以下のコードス ニペットは、上記のプロパティを設定して、集計のカスタム タイトルとカスタム ヘッダーを持つ *Total* 集計タイプの link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] を設定する方法を示しています。

ifdef::wpf[]

*XAML の場合*:

[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  HeaderText="My Custom Data Legend Header"
                  SummaryType="Total"
                  SummaryTitleText="Grand Total"/>
                  
<ig:{FinancialChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*C# の場合*:

[source, cs]
----
dataLegend1.Target = financialChart1;
dataLegend1.HeaderText = "My Custom Data Legend Header";
dataLegend1.SummaryType = Infragistics.Controls.Charts.DataLegendSummaryType.Total;
dataLegend1.SummaryTitleText = "Grand Total";
----

endif::wpf,win-forms[]

== データ凡例の列

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] の列には、タイトル、ラベル、値、および単位の列が含まれます。チャートの各シリーズには、凡例の link:{DataChartLink}.{DataLegendName}{ApiProp}IncludedColumns.html[IncludedColumns] または link:{DataChartLink}.{DataLegendName}{ApiProp}ExcludedColumns.html[ExcludedColumns] コレクションに応じて、ラベル、値、および単位の複数の列を含めることができます。

タイトルの列には、チャートにプロットされた各 `Series` の `Title` プロパティに由来する凡例バッジとシリーズ タイトルが表示されます。

ラベルの列には、凡例の link:{DataChartLink}.{DataLegendName}{ApiProp}IncludedColumns.html[IncludedColumns] または link:{DataChartLink}.{DataLegendName}{ApiProp}ExcludedColumns.html[ExcludedColumns]コレクション内のさまざまなプロパティパスの名前または省略形が表示されます。

値の列には、一連の値が省略形のテキストとして表示されます。この省略形は、link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatAbbreviation.html[ValueFormatAbbreviation] プロパティを使用して書式設定でき、このプロパティを `Auto` または `Shared` に設定することですべての数値に同じ省略形を適用できます。または、ユーザーは `Independent`、`Kilo`、`Million` などの他の省略形を選択できます。省略値の精度は、最小桁数と最大桁数にそれぞれ link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMinFractions.html[ValueFormatMinFractions] と link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMaxFractions.html[ValueFormatMaxFractions] を使用して制御されます。

単位の列には、省略記号や単位テキストが表示されます。これらは、link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsText.html[UnitsText] プロパティを設定することで link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] に設定できます。

link:{DataChartLink}.{DataLegendName}{ApiProp}IncludedColumns.html[IncludedColumns] および link:{DataChartLink}.{DataLegendName}{ApiProp}ExcludedColumns.html[ExcludedColumns] コレクションに含まれる列は、通常、基になるデータ項目の値パスに対応しますが、ファイナンシャル シリーズには、正しくプロットするために必要な `High`、`Low`、`Open`、`Close` パス、および、いくつかの特別なパスを含めるオプションがあります 。凡例内に `TypicalPrice`、`Change`、および `Volume` オプションを表示することができます。

次のコードスニペットは、link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsText.html[UnitsText] と link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] に設定された最小/最大の端数を示しています。

ifdef::wpf[]

*XAML の場合*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  UnitsText="K"
                  ValueFormatMinFractions="2"
                  ValueFormatMaxFractions="4"/>
                  
<ig:{FinancialChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*C# の場合*:

[source, cs]
----
dataLegend1.Target = financialChart1;
dataLegend1.UnitsText = "K";
dataLegend1.ValueFormatMinFractions = 2;
dataLegend1.ValueFormatMaxFractions = 4;
----

endif::wpf,win-forms[]

== データ凡例のスタイル設定

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] は、各タイプの列をスタイル設定するためのプロパティを提供します。これらの各プロパティ名は、Title、Label、Value、Units で始まり、テキストの色、フォント、およびマージンのスタイルを設定できます。たとえば、これらのそれぞれのテキストの色を設定する場合は、link:{DataChartLink}.{DataLegendName}{ApiProp}TitleTextColor.html[TitleTextColor]、link:{DataChartLink}.{DataLegendName}{ApiProp}LabelTextColor.html[LabelTextColor]、link:{DataChartLink}.{DataLegendName}{ApiProp}ValueTextColor.html[ValueTextColor]、および link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsTextColor.html[UnitsTextColor] プロパティを設定します。


以下のコード スニペットは、上記のスタイル設定プロパティを設定する方法を示しています。

ifdef::wpf[]

*XAML の場合*:
[source,xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  TitleTextColor="LightGray"
                  LabelTextColor="LightGray"
                  ValueTextColor="Green"
                  UnitsTextColor="Green"
                  UnitsText="K"/>
                  
<ig:{FinancialChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*C# の場合*:

[source, cs]
----
dataLegend1.Target = financialChart1;
dataLegend1.TitleTextColor = Brushes.LightGray;
dataLegend1.LabelTextColor = Brushes.LightGray;
dataLegend1.ValueTextColor = Brushes.Green;
dataLegend1.UnitsTextColor = Brushes.Green;
dataLegend1.UnitsText = "K";
----

endif::wpf,win-forms[]

== データ凡例値の書式設定

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] は、その link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatAbbreviation.html[ValueFormatAbbreviation] プロパティを使用して、大きな数の自動省略形を提供します。これにより、単位の列に kilo、million、billion などの乗数が追加されます。

link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMinFractions.html[ValueFormatMinFractions] および link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMaxFractions.html[ValueFormatMaxFractions] を設定することにより、表示される小数桁数をカスタマイズできます。これにより、小数点以下に表示される最小桁数と最大桁数をそれぞれ決定できます。

以下のコード スニペットは、link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] の最小分数と最大分数を設定する方法を示しています。

ifdef::wpf[]

*XAML の場合*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                          ValueFormatMinFractions="2"
                          ValueFormatMaxFractions="4"/>
                          
<ig:{FinancialChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*C# の場合*:

[source, cs]
----
dataLegend1.Target = financialChart1;
dataLegend1.ValueFormatMinFractions = 2;
dataLegend1.ValueFormatMaxFractions = 4;
----

endif::wpf,win-forms[]

== データ凡例の値モード

コントロールの link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMode.html[ValueFormatMode] プロパティを変更することにより、link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] 内の値のデフォルトの 10 進表示を通貨に変更することができます。link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] は、link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatCulture.html[ValueFormatCulture] プロパティを使用し、対応するカルチャ タグに設定することにより、表示されている通貨記号のカルチャを変更する機能も公開します。

たとえば、以下のコード スニペットは、link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatCulture.html[ValueFormatCulture] が "en-GB" に設定され、link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMode.html[ValueFormatMode] が "Currency" に設定された link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] を作成します。

ifdef::wpf[]

*XAML の場合*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  ValueFormatMode="Currency"
                  ValueFormatCulture="en-GB"/>
                  
<ig:{FinancialChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*C# の場合*:

[source, cs]
----
dataLegend1.Target = financialChart1;
dataLegend1.ValueFormatMode = Infragistics.Controls.Charts.DataLegendValueMode.Currency;
dataLegend1.ValueFormatCulture = "en-GB";
----

endif::wpf,win-forms[]

== データ凡例のスタイル設定イベント

link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] には、対応する行を描画するときに発生する 5 つのイベントがあります。それらのイベントを、その使用目的とあわせて以下に示します:

- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleHeaderRow_ev.html[StyleHeaderRow]: このイベントは、ヘッダー行を描画するときに 1 回発生します。
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesRow_ev.html[StyleSeriesRow]: このイベントは、シリーズの行ごとに 1 回発生し、シリーズの値の条件付きスタイル設定を可能にします。
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesColumn_ev.html[StyleSeriesColumn]: このイベントは、シリーズ列ごとに 1 回発生します。これにより、チャート内のシリーズのさまざまな列の条件付きスタイルが可能になります。
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSummaryRow_ev.html[StyleSummaryRow]: このイベントは、集計行を描画するときに 1 回発生します。
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSummaryColumn_ev.html[StyleSummaryColumn]: このイベントは、集計列を描画するときに 1 回発生します。

上記の各イベントは、引数として link:{DataChartLink}.DataLegendStylingRowEventArgs.html[DataLegendStylingRowEventArgs]` パラメーターを公開します。これにより、各項目のテキスト、テキストの色、および行の全体的な可視性をカスタマイズできます。イベント引数は、イベント固有のプロパティも公開します。たとえば、link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesRow_ev.html[StyleSeriesRow] イベントはシリーズごとに発生するため、イベント引数は、シリーズを表す行の、シリーズ インデックスとシリーズ タイトルを返します。

以下のコード スニペットは、上記のイベントの使用法を示しています。

ifdef::wpf,win-forms[]

*C# の場合*:
[source, cs]
----
private void Legend_StyleSummaryRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.TitleText = "Grand Total: ";
    row.TitleTextColor = Brushes.DimGray;
}

private void Legend_StyleSeriesRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.BadgeShape = Infragistics.Controls.Charts.LegendItemBadgeShape.Square;
    row.TitleText = (row.SeriesIndex + 1) + ". " + row.SeriesTitle;
    row.TitleTextColor = new SolidColorBrush(Colors.DimGray);
}

private void Legend_StyleHeaderRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.TitleText = "Date: " + row.TitleText; 
    row.TitleTextColor = Brushes.DimGray;
}
----

endif::wpf,win-forms[]