////
|metadata|
{
    "tags": ["Charting","How Do I","Navigation"],
    "controlName": ["financial-chart"]
}
|metadata|
////

= チャート ナビゲーション

== トピックの概要

=== 目的

このトピックは、コード例を使って、link:{FinancialChartLink}.{FinancialChartName}.html[{FinancialChartName}] コントロール内のナビゲーション用途のプロパティと、その使用方法を示します。

=== 前提条件

以下の表は、このトピックを理解するための前提条件として必要なトピックを示しています。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:financial-chart-overview.html[{FinancialChartName}]
|このトピックでは、{FinancialChartName} コントロール シリーズの概要を説明します。

|====

=== このトピックの内容

このトピックは、以下のセクションで構成されます。

* <<Introduction,概要>>
* <<CodeExample,コード例>>
* <<RelatedContent,関連コンテンツ>>

[[Introduction]]
== 概要

{FinancialChartName} コントロールでは、チャート ナビゲーションはデフォルトで有効になっています。以下のプロパティは、ナビゲーション動作を構成するために使用できます。

[options="header", cols="a,a,a,a"]
|====
|プロパティ名 |プロパティ型 2+|説明

ifdef::wpf[]
|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isHorizontalZoomEnabled{HtmlApiExtension}[IsHorizontalZoomEnabled]
|`boolean`
2+|チャートがユーザー操作により水平方向にズーム可能かどうか。デフォルトでこのプロパティは `true` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isVerticalZoomEnabled{HtmlApiExtension}[IsVerticalZoomEnabled]
|`boolean`
2+|チャートがユーザー操作により垂直方向にズーム可能かどうか。デフォルトでこのプロパティは `false` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isWindowSyncedToVisibleRange{HtmlApiExtension}[IsWindowSyncedToVisibleRange]
|`boolean`
2+|true に設定される場合、Y 軸は表示データ範囲に自動的にサイズ変更します。デフォルトでこのプロパティは `false` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}windowRect{HtmlApiExtension}[WindowRect]
|`Rect`
2+|{FinancialChartName} のスクロール状態およびズーム状態を取得または設定するために使用できます。 +
WindowRect は、 0 ~ 1 の間の座標およびサイズの Rectangle として表現されます。

endif::wpf[]

ifdef::jquery[]
|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isHorizontalZoomEnabled{HtmlApiExtension}[isHorizontalZoomEnabled]
|`bool`
2+|チャートがユーザー操作により水平方向にズーム可能かどうか。デフォルトでこのプロパティは `true` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isVerticalZoomeEabled{HtmlApiExtension}[isVerticalZoomEnabled]
|`bool`
2+|チャートがユーザー操作により垂直方向にズーム可能かどうか。デフォルトでこのプロパティは `false` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isWindowSyncedToVisibleRange{HtmlApiExtension}[isWindowSyncedToVisibleRange]
|`bool`
2+|true に設定される場合、Y 軸は表示データ範囲に自動的にサイズ変更します。デフォルトでこのプロパティは `false` に設定されます。

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}windowRect{HtmlApiExtension}[windowRect]
|`object`
2+|{FinancialChartName} のスクロール状態およびズーム状態を取得または設定するために使用できます。 +
WindowRect は、 0 ~ 1 の間の座標およびサイズの Rectangle として表現されます。 +
提供されたオブジェクトは、left、top、width および height と呼ばれる数値プロパティを持っている必要があります。

endif::jquery[]

|====

[[CodeExample]]
== コード例

以下のコード スニペットは、{FinancialChartName} コントロールでチャート ナビゲーションを構成する方法を示します。

ifdef::jquery[]
*JavaScript の場合:*
[source,javascript]
----
$(".selector").{FinancialChartName}({
    isWindowSyncedToVisibleRange: true,
    isVerticalZoomEnabled: false,
    isHorizontalZoomEnabled: true
});
----
endif::jquery[]

ifdef::xaml[]
*XAML の場合:*
[source,xaml]
----
<ig:{FinancialChartName} x:Name="chart"
    IsWindowSyncedToVisibleRange="True"
    IsVerticalZoomEnabled="False"
    IsHorizontalZoomEnabled="True">
</ig:{FinancialChartName}>
----
endif::xaml[]

ifdef::wpf[]
*C# の場合:*
[source,csharp]
----
var chart = new {FinancialChartName}();
chart.IsWindowSyncedToVisibleRange = true;
chart.IsVerticalZoomEnabled = false;
chart.IsHorizontalZoomEnabled = true;
----

*Visual Basic の場合:*
[source,vb]
----
Dim chart = New {FinancialChartName}()
chart.IsWindowSyncedToVisibleRange = True
chart.IsVerticalZoomEnabled = False
chart.IsHorizontalZoomEnabled = True
----
endif::wpf[]

[[RelatedContent]]
== 関連コンテンツ

=== トピック

このトピックに関連する追加情報については、以下のトピックを参照してください。

[options="header", cols="a,a"]
|====
|トピック |目的

|link:financial-chart-pane-zoom.html[ズーム ペイン]
|このトピックは、{FinancialChartName} のズーム ペインを説明します。

|====