////
|metadata|
{
    "name": "xambarcode",
    "controlName": ["{BarcodesName}"],
    "tags": [],
    "guid": "63705612-1a06-4fe1-ac35-29436ba75060",
    "buildFlags": [],
    "createdOn": "2015-09-23T20:37:25.5871327Z"
}
|metadata|
////

= {BarcodesName}

This section gives you an overview of the use of the {BarcodesName}™ family of controls. It contains information ranging from what the series of controls does to the step-by-step procedures on how to accomplish common tasks using the controls.

Click the links below to access important information about the {BarcodesName} family of controls.

== Understanding {BarcodesName}

The topics listed here will give you an overview of the supported symbologies and a better idea of why you would want to use the {BarcodesName} controls in your application.

* link:xambarcode-about-xambarcode.html[About {BarcodesName}]
* link:xambarcode-barcode-symbologies.html[Barcode Symbologies]
* link:xambarcode-settings.html[Configuration Settings]

== link:xambarcode-getting-started-with-xambarcode.html[Getting Started with {BarcodesName}]

In order to get you up and running as quickly as possible with the {BarcodesName} family of control, we've provided you with information on how to get started using the controls.

== link:xambarcode-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the {BarcodesName} family of controls. The namespaces and classes listed in this topic link conveniently into the link:xambarcode-api-overview.html[API Reference Guide] section of the {ProductName} help.