////
|metadata|
{
    "name": "xambarcode-settings",
    "controlName": ["{BarcodesName}"],
    "tags": [],
    "guid": "b3ecf6a0-1908-4852-880c-91c56a79aa96","buildFlags": [],
    "createdOn": "2015-09-23T20:41:05.9379316Z"
}
|metadata|
////

= Configuration Settings

This section gives you an overview of settings in the {BarcodesName}™ family of controls.

== Before You Begin

If you do not set a Width or Height value of the Barcode, it is sized according to its container. Setting the Height and Width creates a containing rectangular area that the symbol is displayed in. You can specify how the symbol fills this containing area using the following properties:

* link:xambarcode-xdimension.html[Configuring XDimension]
ifdef::wpf,win-forms,android[]
* link:xambarcode-widthtoheightratio.html[Configuring WidthToHeight Ratio]
endif::wpf,win-forms,android[]
* link:xambarcode-barsfillmode.html[Configuring Bars Fill Mode]
ifdef::xaml,win-forms[]
* link:xambarcode-stretch.html[Configuring Stretch]
endif::xaml,win-forms[]