////
|metadata|
{
    "name": "xambarcode-about-xambarcode",
    "controlName": ["{BarcodesName}"],
    "tags": [],
    "guid": "0a470afd-160c-4ac5-9690-e92335c26e78","buildFlags": [],
    "createdOn": "2015-09-23T20:38:46.2797104Z"
}
|metadata|
////

= About {BarcodesName}

From shipping containers, to medical records, to a can of beans at the grocery store, barcodes have become the universal mechanism for affixing identifying data to physical assets. Industries have created standards around barcode technology such as creating barcodes that provide capabilities unique to their industries. The vision for the barcode control is to provide you with a set of controls that are capable of rendering on screen barcode images that conform to the various widely adopted barcodes standards; these controls abstract much of the process and detail of barcode creation from developers, allowing them to easily embed data in barcode format into their applications.

The {BarcodesName}™ family of controls provides support for the following barcode symbologies pick:[wpf,android,win-forms="(note that each barcode is a separate control)"]:

* link:xambarcode-configuring-qr-code.html[Configuring QR Code]
ifdef::wpf,win-forms,android[]
* link:xambarcode-configuring-code128.html[Configuring Code 128]
endif::wpf,win-forms,android[]
ifdef::wpf,win-forms[]
* link:xambarcode-xamcode39barcode.html[Code 39]
* link:xambarcode-xameanupcbarcode.html[Ean/Upc]
* link:xambarcode-xaminterleaved2of5barcode.html[Interleaved 2 Of 5]
* link:xambarcode-xamgs1databarbarcode.html[GS1 DataBar]
* link:xambarcode-xamintelligentmailbarcode.html[Intelligent Mail]
* link:xambarcode-xamroyalmailbarcode.html[Royal Mail]
* link:xambarcode-xampdf417barcode.html[PDF 417]
* link:xambarcode-xammaxicodebarcode.html[Maxi Code]
endif::wpf,win-forms[]

== Related Topics

* link:xambarcode-barcode-symbologies.html[Barcode Symbologies]