////
|metadata|
{
    "name": "xambarcode-getting-started-with-xambarcode",
    "controlName": ["{BarcodesName}"],
    "tags": [],
    "guid": "3f3896c2-c32b-44f2-90b8-1312f9c0fca8","buildFlags": [],
    "createdOn": "2015-09-23T20:38:18.8297612Z"
}
|metadata|
////

= Getting Started with {BarcodesName}

Click on a topic below to find information on how to get up and running quickly with the {BarcodesName}™ series of controls. You will learn how to create a sample pick:[wpf="page"]  pick:[android,win-forms,xamarin="application"] using the control.

This topic provides resources on how to get started with the {BarcodesName}™ control.

* link:xambarcode-adding-barcode-in-code-behind.html[Adding Barcode Using Code-Behind]

ifdef::xaml[]

* link:xambarcode-adding-xambarcode-using-xaml.html[Adding Barcode Using XAML Code]

endif::xaml[]

* link:xambarcode-databinding.html[Binding Data]

ifdef::wpf,win-forms[]
* link:xambarcode-hidingbarcodetext.html[Hiding Barcode Text]

endif::wpf,win-forms[]

ifdef::xaml,win-forms[]
* link:xambarcode-eventhandling.html[Handling Events]

endif::xaml,win-forms[]

== Related Topics

* link:xambarcode-api-overview.html[API Overview]