////
|metadata|
{
    "name": "scheduler-binding-schedulelistdatasource",
    "controlName": ["scheduler"],
    "tags": [],
    "guid": "","buildFlags": [],
    "createdOn": "2017-03-30T09:37:02.0484523Z"
}
|metadata|
////

= ScheduleListDataSource とデータへのバインド ({SchedulerName})

== 目的

このトピックでは、コントロールを ScheduleListDataSource を使用してデータ ソースへバインドする方法を説明します。

== 前提条件

[options="header", cols="a,a"]
|=======
|トピック|目的

|link:scheduler-overview.html[概要 ({SchedulerName})]
|このトピックでは、{SchedulerName} コントロール シリーズの概要を説明します。

|=======

== このトピックの構成

* <<Ref00001, 概要>>
* <<Ref00002, 主なプロパティ>>
* <<Ref00003, コード例>>
* <<Ref00004, 関連トピック>>

[[Ref00001]]
== 概要

link:{SchedulerXFLink}.xamscheduler.html[{SchedulerName}] コントロールを link:{SchedulerXFLink}.xamscheduler~datasource.html[DataSource] プロパティでデータ ソースにバインドできます。このプロパティは link:{SchedulerXFLink}.scheduledatasource.html[ScheduleDataSource] 型のオブジェクトを承諾します。この抽象基本クラスの実装は link:{SchedulerXFLink}.schedulelistdatasource.html[ScheduleListDataSource] クラスです。

[[Ref00002]]
== 主なプロパティ

以下の表は、`ScheduleListDataSource` のインスタンスを構成する主なプロパティをリストします。

[options="header", cols="a,a"]
|=======
|プロパティ|目的
|link:{SchedulerXFLink}.schedulelistdatasource~appointmentitemssource.html[AppointmentItemsSource]
|このプロパティを `IEnumerable` インターフェイスを実装するオブジェクトに設定し、コントロールで使用する link:{SchedulerCoreLink}.appointment.html[Appointment] のセットを提供できます。
|link:{SchedulerXFLink}.schedulelistdatasource~resourceitemssource.html[ResourceItemsSource]
|このプロパティを `IEnumerable` インターフェイスを実装するオブジェクトに設定し、コントロールで使用する link:{SchedulerCoreLink}.scheduleresource.html[ScheduleResource] のセットを提供します。
|=======

.注:
[NOTE]
====
カスタム オブジェクト型をアクティビティおよびリソースで使用できますが、プロパティ マッピングを定義する必要があります。この手順は「link:scheduler-binding-custom-types.html[カスタム エンティティ型の使用 ({SchedulerName})]」トピックで説明されます。
====

[[Ref00003]]
== コード例

以下のコードは、XAML で {SchedulerName} コントロールを作成し、データ ソースを `ScheduleListDataSource` のインスタンスに設定する方法を紹介します。`ScheduleListDataSource` の予定およびリソースはバインディング コンテキストで `Appointments` および `Resources` フィールドにバインドされます。

*XAML の場合:*
[source,xaml]
----
<ig:XamScheduler>
    <ig:XamScheduler.DataSource>
        <ig:ScheduleListDataSource
            AppointmentItemsSource="{Binding Appointments}"
            ResourceItemsSource="{Binding Resources}" />
    </ig:XamScheduler.DataSource>
</ig:XamScheduler>
----

以下のコードは、1 つの予定がある `ScheduleListDataSource` を作成し、「scheduler1」という名前の {SchedulerName} コントロールに設定する方法を示します。

*C# の場合:*
[source,csharp]
----
ObservableCollection<Appointment> appointments = new ObservableCollection<Appointment>();
appointments.Add(new Appointment()
{
    Start = DateTime.Now,
    End = DateTime.Now,
    Subject = "Daily Meeting 1",
    Location = "Conference Room #1",
    ResourceId = "ID1"
});

ScheduleListDataSource listDataSource = new ScheduleListDataSource();
listDataSource.AppointmentItemsSource = appointments;

this.scheduler1.DataSource = listDataSource;
----

[[Ref00004]]
== 関連トピック

[options="header", cols="a,a"]
|=======
|トピック|目的

|link:scheduler-binding-custom-types.html[カスタム エンティティ型の使用 ({SchedulerName})]
|このトピックでは、コントロールをカスタム エンティティ型を使用するデータ ソースへバインドする方法を説明します。

|link:scheduler-appointment.html[予定 ({SchedulerName})]
|このトピックは Appointment アクティビティ型を説明します。

|link:scheduler-resources.html[リソース ({SchedulerName})]
|このトピックは、{SchedulerName} コントロールのリソース概念について説明します。

|=======