////
|metadata|
{
    "name": "excelengine-workbook-protection",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Editing","How Do I","Tips and Tricks"],
    "guid": "3d76a3bd-9ef2-4fae-ba7c-681a70a07c64",
    "buildFlags": [],
    "createdOn": "2014-12-02T09:13:49.7036918Z"
}
|metadata|
////

= Workbook Protection ({ExcelEngineName})

== Topic Overview

=== Purpose

This topic explains how to set, remove and configure workbook protection.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:excelengine-about-infragistics-excel-engine.html[About {ExcelEngineName}]
|In this section you will find information that will help you to better understand the object model and the functionalities of the {ExcelEngineName}.

| link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]
|In order to get you up and running as quickly as possible with the {ExcelEngineName}, this topic provides procedural instructions on how to create a workbook.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref404698209, Workbook Protection >>
* <<_Ref404698240, Related Content >>

[[_Ref404698209]]
== Workbook Protection

=== Summary

The workbook protection feature allows you to protect (with or without password) the following user operations:

* Window protection: the ability to resize the MDI child window of the workbook for legacy versions of MS Excel which were displaying each workbook in a separate child window.
* Workbook structure: the ability to add, rename, delete, hide and reorder the worksheets.

.Note
[NOTE]
====
The protection is not enforced via the {ExcelEngineName}'s object model. It is a responsibility of the UI visualizing this object model, to honor these protection settings and allow or restrict the user from performing the corresponding operations.
====

=== Configuration chart

The following table explains briefly the functional aspects of the workbook protection feature and maps them to the properties and methods that operate with them.

[options="header", cols="a,a,a"]
|====
|Operation|Details|Property/Method

|Set workbook protection
|
ifdef::wpf[]
You can use the overloads of the `Protect` method to protect the workbook with password (supplied using `string` or `SecureString`) or without password. The other arguments of this method are used to specify each protection setting described above.
endif::wpf[]
ifdef::xamarin[]
You can use the `Protect` method to protect the workbook. The arguments of this method allow you to specify each protection setting described above.
endif::xamarin[]
| link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~protect.html[Protect]

|Remove workbook protection
|
ifdef::wpf[]
You can use the overloads of the `Unprotect` method to remove workbook protection set with or without password. 

If the password supplied to the `Unprotect` methods does not match the password set on the workbook an exception will be thrown. 

.Note 
[NOTE] 
==== 
You can use the `Unprotect` overload method without password argument to remove protection even on password protected workbooks. 
====
endif::wpf[]
ifdef::xamarin[]
You can use the `Unprotect` method to remove workbook protection set with or without password.
endif::xamarin[]
| link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~unprotect.html[Unprotect]

|Check if a workbook has protection
|This read-only property returns true if the workbook has any protection set using the pick:[wpf="overloads of the"] `Protect` method.
| link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~isprotected.html[IsProtected]

|Check if a workbook has password protection
|This read-only property returns true if the workbook has password protection.
| link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~hasprotectionpassword.html[HasProtectionPassword]

|Obtain workbook protection
|This read-only property returns an object of type link:{ExcelEngineApiLink}infragistics.documents.excel.workbookprotection.html[WorkbookProtection] which contains properties for obtaining each protection setting individually.
| link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~protection.html[Protection]

|====

[[_Ref404698240]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:excelengine-password-support.html[Password Support ({ExcelEngineName})]
|This topic explains how to operate with password encrypted files.

| link:excelengine-worksheet-protection.html[Worksheet Protection ({ExcelEngineName})]
|This topic explains how to set, remove and configure worksheet protection.

|====