////
|metadata|
{
    "name": "excelengine-load-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","Getting Started","How Do I"],
    "guid": "{F630174F-D7A0-4745-91E1-F2A8B643B4EB}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7647061Z"
}
|metadata|
////

= Loading an Excel File ({ExcelEngineName})

ifdef::win-forms,win-forms-old,asp-net,aspnet-old,wpf[]

In addition to creating Microsoft® Excel® files, the {ExcelEngineName} can also read them. You can create a link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] object from an existing Excel file, make some changes, and save a new file containing the modified workbook. When you read an Excel file using the Workbook object's static link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~load.html[Load] method, a Workbook object is created and its object model is populated with all the features supported by the {ExcelEngineName}. Cell values and formats, as well as workbook and worksheet options are all accessible and modifiable from the parsed workbook.

endif::win-forms,win-forms-old,asp-net,aspnet-old,wpf[]
ifdef::xamarin[]

In addition to creating Microsoft® Excel® workbooks, the {ExcelEngineName} can also read them. You can load an Excel workbook by invoking the link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook]'s static link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~load.html[Load] method and provide an input stream to an Excel workbook content source. As a result a Workbook object is created and its object model is populated with all the features supported by the {ExcelEngineName}. Cell values and formats, as well as workbook and worksheet options are all accessible and modifiable from the parsed workbook.

endif::xamarin[]

The following example code demonstrates how to load an existing workbook.

ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
*In Visual Basic:*
[source, vb]
----
Imports Infragistics.Documents.Excel
...
' Load workbook with data
Dim workbook1 As Workbook = Workbook.Load(pick:[wpf=""filename.xls""]pick:[xamarin="inputStream"])
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]

*In C#:*
[source, csharp]
----
using Infragistics.Documents.Excel;
...
// Load workbook with data
Workbook workbook1 = Workbook.Load(pick:[wpf=""filename.xls""]pick:[xamarin="inputStream"]);
----

== Related Topics

link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]

link:excelengine-save-a-workbook.html[Saving a Workbook ({ExcelEngineName})]

link:excelengine-format-a-cell.html[Formatting a Cell ({ExcelEngineName})]

link:excelengine-copy-a-cells-format.html[Copying a Cell's Format ({ExcelEngineName})]

link:excelengine-reference-cells-and-regions.html[Referencing Cells and Regions ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[Merging Cells ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[Merging Cells ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[Adding a Formula to a Cell ({ExcelEngineName})]

link:excelengine-add-a-comment-to-a-cell.html[Adding a Comment to a Cell ({ExcelEngineName})]

link:excelengine-disable-editing-of-a-worksheet.html[Disabling Editing of a Worksheet ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-set-excel-document-properties.html[Setting Workbook Properties ({ExcelEngineName})]