////
|metadata|
{
    "name": "excelengine-format-a-cell",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Editing","Formatting","How Do I"],
    "guid": "{F448B6F1-3C38-4279-AA6B-26D2A1A9C7DB}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7607053Z"
}
|metadata|
////

= Formatting a Cell ({ExcelEngineName})

The {ExcelEngineName} allows you to customize the look and behavior of a cell. You can customize a cell by setting properties exposed by the link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell~cellformat.html[CellFormat] property of the link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell.html[WorksheetCell], link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetrow.html[WorksheetRow], link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn], or link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetmergedcellsregion.html[WorksheetMergedCellsRegion] objects.

You can customize every aspect of a cell's appearance. You can set a cell’s font, background, and borders, as well as text alignment and rotation. You can even apply a different format on a character-by-character basis for a cell’s text.

You can also format cell values by assigning a format string. An acceptable format string follows the .NET standard format and formatting codes.

The following code shows you how to format a cell to display numbers as currency and to color negative values red. The example code assumes you have a reference to a Worksheet named worksheet1.

ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
*In Visual Basic:*
[source,vb]
----
worksheet1.Columns(2).CellFormat.FormatString = """$""#,##0.00;[red](""$""#,##0.00)"
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]

*In C#:*
[source,csharp]
----
worksheet1.Columns[2].CellFormat.FormatString = "\"$\"#,##0.00;[red](\"$\"#,##0.00)";
----

== Related Topics

link:excelengine-about-infragistics-excel-engine.html[About {ExcelEngineName}]

link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]

link:excelengine-load-an-excel-file.html[Loading an Excel File ({ExcelEngineName})]

link:excelengine-save-a-workbook.html[Saving a Workbook ({ExcelEngineName})]

link:excelengine-copy-a-cells-format.html[Copying a Cell's Format ({ExcelEngineName})]

link:excelengine-reference-cells-and-regions.html[Referencing Cells and Regions ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[Merging Cells ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[Merging Cells ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[Adding a Formula to a Cell ({ExcelEngineName})]

link:excelengine-add-a-comment-to-a-cell.html[Adding a Comment to a Cell ({ExcelEngineName})]

link:excelengine-disable-editing-of-a-worksheet.html[Disabling Editing of a Worksheet ({ExcelEngineName})]

link:excelengine-freeze-and-split-panes.html[Freezing and Splitting Panes ({ExcelEngineName})]

link:excelengine-set-excel-document-properties.html[Setting Workbook Properties ({ExcelEngineName})]