////
|metadata|
{
    "name": "excelengine-save-a-workbook",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","How Do I"],
    "guid": "{AD387C75-027C-4411-9E17-7BACFBBC3C2E}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7717075Z"
}
|metadata|
////

= Saving a Workbook ({ExcelEngineName})

You can save a link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] object by calling its link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~save.html[Save] method. However, the workbook must contain at least one visible worksheet when you save it; otherwise, an exception will be thrown.

The following example code demonstrates how to save a Workbook object as an Excel file.

ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
*In Visual Basic:*
[source, vb]
----
Dim workbook1 As New Workbook()
Dim worksheet As Worksheet = workbook1.Worksheets.Add("Sheet1")
' Make some column headers
worksheet.Rows(1).Cells(1).Value = "Morning"
worksheet.Rows(1).Cells(2).Value = "Afternoon"
worksheet.Rows(1).Cells(3).Value = "Evening"
workbook1.Save("filename.xls")
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]

*In C#:*
[source, csharp]
----
Workbook workbook1 = new Workbook();
Worksheet worksheet = workbook1.Worksheets.Add("Sheet1");
// Make some column headers
worksheet.Rows[1].Cells[1].Value = "Morning";
worksheet.Rows[1].Cells[2].Value = "Afternoon";
worksheet.Rows[1].Cells[3].Value = "Evening";
ifdef::wpf[]
workbook1.Save("filename.xls");
endif::wpf[]
ifdef::xamarin[]
workbook1.Save(outputStream);
endif::xamarin[]
----

== Related Topics

link:excelengine-about-infragistics-excel-engine.html[About {ExcelEngineName}]

link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]

link:excelengine-load-an-excel-file.html[Load an Excel File ({ExcelEngineName})]

link:excelengine-format-a-cell.html[Format a Cell ({ExcelEngineName})]

link:excelengine-copy-a-cells-format.html[Copy a Cell's Format ({ExcelEngineName})]

link:excelengine-reference-cells-and-regions.html[Reference Cells and Regions ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[Merging Cells ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[Merging Cells ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[Add a Formula to a Cell ({ExcelEngineName})]

link:excelengine-add-a-comment-to-a-cell.html[Add a Comment to a Cell ({ExcelEngineName})]

link:excelengine-disable-editing-of-a-worksheet.html[Disable Editing of a Worksheet ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-set-excel-document-properties.html[Set Excel Document Properties ({ExcelEngineName})]