////
|metadata|
{
    "name": "excel-engine",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{E6FB9EA1-5649-4078-A890-3FBEA1549CDA}","buildFlags": [],
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.0339599Z"
}
|metadata|
////

= {ExcelEngineName}

This section contains information about the {ExcelEngineName}, ranging from what the engine does and step-by-step procedures on using it in your application.

Click the links below to access important information about the {ExcelEngineName}.

== link:excelengine-about-infragistics-excel-engine.html[About {ExcelEngineName}]

In this section you'll find information that will help you to better understand the object model and the functionalities of the {ExcelEngineName}.

== link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]

In order to get you up and running as quickly as possible with the {ExcelEngineName}, we've provided you with information on how to get started using the {ExcelEngineName} (e.g., creating a workbook).

== link:excelengine-using-the-infragistics-excel-engine.html[Using the {ExcelEngineName}]

This section contains information on the key features and functionalities provided by the {ExcelEngineName}.

== link:excelengine-api-overview.html[API Overview ({ExcelEngineName})]

This topic lists the namespaces and classes that you will be working with while programming with the {ExcelEngineName}. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.