////
|metadata|
{
    "name": "excelengine-reference-cells-and-regions",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting"],
    "guid": "{904B2B76-11A5-4EE1-8B32-1F4B5C0044E6}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7697071Z"
}
|metadata|
////

= Referencing Cells and Regions ({ExcelEngineName})

You can access a link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell.html[WorksheetCell] object or a link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetregion.html[WorksheetRegion] object by calling the Worksheet object's link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~getcell.html[GetCell] or link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~getregion.html[GetRegion] methods, respectively. Both methods accept a string parameter that references a cell. Getting a reference to a cell is useful when applying formats or working with formulas and cell contents. A typical usage of the GetRegion method is shown in *Merging Cells* article (for more information refer to the *Related Topics* section).

The following example code demonstrates how to reference cells and regions. The example code assumes you have a reference to a Worksheet object named worksheet1.

ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
*In Visual Basic:*
[source,vb]
----
Imports Infragistics.Documents.Excel
...
'Accessing a single cell
Dim cellE2 As WorksheetCell = worksheet1.GetCell("E2")
'Accessing a range of cells
Dim regionG As WorksheetRegion = worksheet1.GetRegion("G1:G10")
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]

*In C#:*
[source,csharp]
----
using Infragistics.Documents.Excel;
...
//Accessing a single cell
WorksheetCell cellE2 = worksheet1.GetCell("E2");
//Accessing a range of cells
WorksheetRegion regionG = worksheet1.GetRegion("G1:G10");
----

== Related Topics

link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]

link:excelengine-load-an-excel-file.html[Loading an Excel File ({ExcelEngineName})]

link:excelengine-save-a-workbook.html[Saving a Workbook ({ExcelEngineName})]

link:excelengine-format-a-cell.html[Formatting a Cell ({ExcelEngineName})]

link:excelengine-copy-a-cells-format.html[Copying a Cell's Format ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[Merging Cells ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[Merging Cells ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[Adding a Formula to a Cell ({ExcelEngineName})]

link:excelengine-add-a-comment-to-a-cell.html[Adding a Comment to a Cell ({ExcelEngineName})]

link:excelengine-disable-editing-of-a-worksheet.html[Disabling Editing of a Worksheet ({ExcelEngineName})]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[Freezing and Splitting Panes ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-set-excel-document-properties.html[Setting Workbook Properties ({ExcelEngineName})]