////
|metadata|
{
    "name": "excelengine-grouping-excel-shapes",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","Grouping"],
    "guid": "e5671d23-2e7a-4019-b66f-8de1ddab1cc3",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7827097Z"
}
|metadata|
////

= Grouping Shapes ({ExcelEngineName})

== Topic Overview

== Purpose

This topic demonstrates how to group two or more shapes.

== Required background

You need to first read the following topics:

* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet ({ExcelEngineName})]

== Introduction

A group of shapes is a structure consisting of two or more that behave like one shape. Working with groups of shapes is similar to working with link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet.html[Worksheet Class] and link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape Class].

To group two or more shapes ensure you have the shapes initialized, then initialize a link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup] object and add the shapes to its link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroupbase~shapes.html[Shapes] collection.

The procedure that follows demonstrates how to group two already initialized shapes.

== Grouping Excel Shapes

== Requirements

To complete the procedure, you need the following:

* Initialize two link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape] objects
* Add the result of this procedure to a link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet.html[Worksheet]

== Overview

Following is a conceptual overview of the process:

[start=1]
. *Initialize two shapes*
[start=2]
. *Group the shapes*
[start=3]
. *Set position and size. Add to a worksheet.*

== Steps

[start=1]
. *Initialize two shapes*
+
Name the objects *shape1* and *shape2*. To complete this step refer to the link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet] topic.

[start=2]
. *Group the shapes*
+
Initialize a new link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup] object and add the shapes to its link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroupbase~shapes.html[Shapes] collection.
ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
+
*In Visual Basic:*
+
[source,vb]
----
Dim shapeGroup As New WorksheetShapeGroup()
shapeGroup.Shapes.Add(shape1)
shapeGroup.Shapes.Add(shape2)
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
+
*In C#:*
+
[source,csharp]
----
WorksheetShapeGroup shapeGroup = new WorksheetShapeGroup();
shapeGroup.Shapes.Add(shape1);
shapeGroup.Shapes.Add(shape2);
----

[start=3]
. *Set position and size. Add to a worksheet.*
+
link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup Class] derives from link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape Class], so everything about sizing, positioning, adding to a sheet and etc is the same as link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet].

== Related Topics

Following are some other topics you may find useful.

* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet ({ExcelEngineName})]
* link:excelengine-importing-shapes-from-excel.html[Importing Shapes from Excel ({ExcelEngineName})]