////
|metadata|
{
    "name": "excelengine-worksheet-protection",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Editing","How Do I","Tips and Tricks"],
    "guid": "89158eba-1444-4bfd-b4bf-563c4658c234",
    "buildFlags": [],
    "createdOn": "2014-12-02T09:16:27.0376588Z"
}
|metadata|
////

= Worksheet Protection ({ExcelEngineName})

== Topic Overview

=== Purpose

This topic explains how to set, remove and configure worksheet protection.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:excelengine-about-infragistics-excel-engine.html[About {ExcelEngineName}]
|In this section you will find information that will help you to better understand the object model and the functionalities of the {ExcelEngineName}.

| link:excelengine-creating-a-workbook.html[Creating a Workbook ({ExcelEngineName})]
|In order to get you up and running as quickly as possible with the {ExcelEngineName}, this topic provides procedural instructions on how to create a workbook.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref404784892, Worksheet Protection >>
* <<_Ref404784902, Related Content >>

[[_Ref404784892]]
== Worksheet Protection

=== Summary

The worksheet protection feature allows you to protect pick:[wpf="(with or without password)"] the following user operations:

* Inserting, deleting and formatting of columns
* Inserting, deleting and formatting of rows
* Inserting of hyperlinks
* Editing of objects (this setting allows or restricts editing of shapes, comments, charts or controls may be created or changed)
* Editing of scenarios (this setting allows or restricts existing scenarios)
* Filtering of data (this setting allows or restricts the use of auto filters)
* Formatting of cells (this setting allows or restricts the user from changing cells' formatting)
* Sorting of data
* Pivot tables (this setting allows or restricts the user from changing pivot tables)
* Cells editing (this setting allows or restricts the user from editing cells' value by providing cell ranges which can be edited when in protected mode)
* Cells selection (this setting allows or restricts the user selection to all cells, unlocked cells only or no selection)

.Note
[NOTE]
====
The protection is not enforced via the Infragistics Excel Engine's object model. It is a responsibility of the UI visualizing this object model, to honor these protection settings and allow or restrict the user from performing the corresponding operations.
====

=== Configuration chart

The following table explains briefly the functional aspects of the worksheet protection feature and maps them to the properties and methods that operates with them.

[options="header", cols="a,a,a"]
|====
|Operation|Details|Properties

|Set worksheet protection
|
ifdef::wpf[]
You can use the overloads of the `Protect` method to protect the worksheet with password (supplied using `string` or `SecureString`) or without password. The other arguments of this method are used to specify each protection setting described above.
endif::wpf[]
ifdef::xamarin[]
You can use the `Protect` method to protect the worksheet. The arguments of this method allow you to specify each protection setting described above.
endif::xamarin[]
| link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~protect.html[Protect]

|Remove worksheet protection
|
ifdef::wpf[]
You can use the overloads of the `Unprotect` method to remove worksheet protection set with or without password. 

If the password supplied to the `Unprotect` methods does not match the password set on the worksheet an exception will be thrown. 

.Note 
[NOTE] 
==== 
You can use the `Unprotect` overload method without password argument to remove protection even on password protected worksheets. 
====
endif::wpf[]
ifdef::xamarin[]
You can use the `Unprotect` method to remove worksheets protection set with or without password.
endif::xamarin[]
| link:{ExcelEngineApiLink}infragistics.documents.excel.sheet~unprotect.html[Unprotect]

|Check if a worksheet has protection
|This read-only property returns true if the worksheet has any protection set using the pick:[wpf="overloads of the"] `Protect` method.
| link:{ExcelEngineApiLink}infragistics.documents.excel.sheet~isprotected.html[IsProtected]

|Check if a worksheet has password protection
|This read-only property returns true if the worksheet has password protection.
| link:{ExcelEngineApiLink}infragistics.documents.excel.sheet~hasprotectionpassword.html[HasProtectionPassword]

|Obtain worksheet protection
|This read-only property returns an object of type link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetprotection.html[WorksheetProtection] which contains properties for obtaining each protection setting individually.
| link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~protection.html[Protection]

|====

[[_Ref404784902]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:excelengine-password-support.html[Password Support ({ExcelEngineName})]
|This topic explains how to operate with password encrypted files.

| link:excelengine-workbook-protection.html[Workbook Protection ({ExcelEngineName})]
|This topic explains how to set, remove and configure workbook protection.

|====