////
|metadata|
{
    "name": "excelengine-importing-shapes-from-excel",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["How Do I"],
    "guid": "034a215d-da9c-4c0a-a360-641ad028a192",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7857103Z"
}
|metadata|
////

= Importing Shapes from Excel ({ExcelEngineName})

== Topic Overview

== Purpose

This topic shows you how to enumerate shapes from an Excel file.

== Required background

You need to first read the following topics:

* link:excelengine-load-an-excel-file.html[Loading an Excel File ({ExcelEngineName})]
* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet ({ExcelEngineName})]

== Control Configuration Overview

== Control configuration chart

The table below lists the configurable behaviors of the {ExcelEngineName}.

[options="header", cols="a,a,a"]
|====
|Configuration behaviour|Configuration details|Configuration properties

|Enumerate shapes from an Excel file
|Read all shape instances from a worksheet
| link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~shapes.html[Worksheet.Shapes]

|====

== Enumerate shapes from an Excel file

== Example description

You can enumerate the existing shapes in a worksheet by first loading the file into a link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] instance. Then, using the link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~worksheets.html[Workbook.Worksheets collection], get the link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet.html[Worksheet] instance and enumerate its link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~shapes.html[Shapes property]. This property is a link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapecollection.html[WorksheetShapeCollection], which can be used to enumerate or modify the shapes on a Worksheet.

ifdef::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]
*In Visual Basic:*
[source,vb]
----
Dim book As Workbook = Workbook.Load("..\..\test.xlsx")
For Each sheet As Worksheet In book.Worksheets
    For Each shape As WorksheetShape In sheet.Shapes
    Dim bounds As Rect = shape.GetBoundsInTwips()
        Console.WriteLine(
            [String].Format("ClassName:{0} – Bounds:{1},{2},{3},{4}",
                shape.[GetType](),
                bounds.X,
                bounds.Y,
                bounds.Width,
                bounds.Height))
    Next
Next
----
endif::asp-net,aspnet-old,win-forms,win-forms-old,wpf[]

*In C#:*
[source,csharp]
----
ifdef::wpf[]
Workbook book = Workbook.Load(@"..\..\test.xlsx");
endif::wpf[]
ifdef::xamarin[]
Workbook book = Workbook.Load(inputStream);
endif::xamarin[]
foreach (Worksheet sheet in book.Worksheets)
{
    foreach (WorksheetShape shape in sheet.Shapes)
    {
        pick:[wpf="Rect"]pick:[xamarin="Rect"] bounds = shape.GetBoundsInTwips();
        pick:[wpf="Console.WriteLine("]pick:[xamarin="System.Diagnostics.Debug.WriteLine("]
            String.Format("ClassName:{0} – Bounds:{1},{2},{3},{4}",
                shape.GetType(),
                bounds.X,
                bounds.Y,
                bounds.Width,
                bounds.Height));
    }
}
----

== Related Topics

Following are some other topics you may find useful.

* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[Adding a Shape to a Worksheet ({ExcelEngineName})]
* link:excelengine-customizing-excel-shapes.html[Customizing Shapes ({ExcelEngineName})]
* link:excelengine-grouping-excel-shapes.html[Grouping Shapes ({ExcelEngineName})]