= Data Legend

The link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] is a component that works much like the `Legend`, but it shows values of series and provides many configuration properties for filtering series rows and values columns, styling and formatting values. This legend updates when moving the mouse inside of the plot area of the link:{DataChartLink}.{CategoryChartName}.html[{CategoryChartName}] and has a persistent state that remembers the last hovered point when the user's mouse pointer exits the plot area. It displays this content using a set of three type of rows and four types of columns.

== Data Legend Rows

The rows of the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] include the header row, series row(s), and the summary row.

The header row displays the axis label of the point that is hovered, and can be changed using the link:{DataChartLink}.{DataLegendName}{ApiProp}HeaderText.html[HeaderText] property.

The series row can actually be a set of rows corresponding to each series plotted in the chart. These rows will display the legend badge, series title, actual/abbreviated value of the the series, and abbreviation symbol and unit, if specified.

Finally, there is a summary row that displays the total of all series values. The default summary title can be changed using the link:{DataChartLink}.{DataLegendName}{ApiProp}SummaryTitleText.html[SummaryTitleText] property of the legend. Also, you can use the link:{DataChartLink}.{DataLegendName}{ApiProp}SummaryType.html[SummaryType] property to customize whether you display the Total, Min, Max, or Average of series values in the summary row.

The following code snippet demonstrates setting the properties mentioned above to have a link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] with a **Total** summary type with a custom title for the summary and a custom header:

ifdef::wpf[]

*In XAML*:

[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  HeaderText="My Custom Data Legend Header"
                  SummaryType="Total"
                  SummaryTitleText="Grand Total"/>
                  
<ig:{CategoryChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*In C#*:

[source, cs]
----
dataLegend1.Target = categoryChart1;
dataLegend1.HeaderText = "My Custom Data Legend Header";
dataLegend1.SummaryType = Infragistics.Controls.Charts.DataLegendSummaryType.Total;
dataLegend1.SummaryTitleText = "Grand Total";
----

endif::wpf,win-forms[]

== Data Legend Columns

The columns of the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] include the title, label, value, and units columns. Each series in the chart can have multiple columns for label, value, and units depending on the link:{DataChartLink}.{DataLegendName}{ApiProp}IncludedColumns.html[IncludedColumns] or link:{DataChartLink}.{DataLegendName}{ApiProp}ExcludedColumns.html[ExcludedColumns] collections of the legend.

The title column displays legend badges and series titles, which come from the `Title` property of the different `Series` plotted in the chart.

The label column displays the name or abbreviation of the different property paths in the link:{DataChartLink}.{DataLegendName}{ApiProp}IncludedColumns.html[IncludedColumns] or link:{DataChartLink}.{DataLegendName}{ApiProp}ExcludedColumns.html[ExcludedColumns] collections of the legend.

The value column displays series values as abbreviated text which can be formatted using the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatAbbreviation.html[ValueFormatAbbreviation] property to apply the same abbreviation for all numbers by setting this property to `Auto` or `Shared`. Alternatively, a user can select other abbreviations such as `Independent`, `Kilo`, `Million`, etc. Precision of abbreviated values is controlled using the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMinFractions.html[ValueFormatMinFractions] and link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMaxFractions.html[ValueFormatMaxFractions] for minimum and maximum digits, respectively.

The units column displays an abbreviation symbol and/or unit text, which can be set either on the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] by setting the link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsText.html[UnitsText] property.

The following code snippet demonstrates the link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsText.html[UnitsText] and the minimum/maximum fractions set on the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}]:

ifdef::wpf[]

*In XAML*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  UnitsText="K"
                  ValueFormatMinFractions="2"
                  ValueFormatMaxFractions="4"/>
                  
<ig:{CategoryChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*In C#*:

[source, cs]
----
dataLegend1.Target = categoryChart1;
dataLegend1.UnitsText = "K";
dataLegend1.ValueFormatMinFractions = 2;
dataLegend1.ValueFormatMaxFractions = 4;
----

endif::wpf,win-forms[]

== Data Legend Styling

The link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] provides properties for styling each type of column. Each of these properties begins with Title, Label, Value, or Units, and you can style the text's color, font, and margin. For example, if you wanted to set the text color of each of these, you would set the link:{DataChartLink}.{DataLegendName}{ApiProp}TitleTextColor.html[TitleTextColor], link:{DataChartLink}.{DataLegendName}{ApiProp}LabelTextColor.html[LabelTextColor], link:{DataChartLink}.{DataLegendName}{ApiProp}ValueTextColor.html[ValueTextColor], and link:{DataChartLink}.{DataLegendName}{ApiProp}UnitsTextColor.html[UnitsTextColor] properties.

The following code snippet demonstrates how to set the styling properties mentioned above:

ifdef::wpf[]

*In XAML*:
[source,xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  TitleTextColor="LightGray"
                  LabelTextColor="LightGray"
                  ValueTextColor="Green"
                  UnitsTextColor="Green"
                  UnitsText="K"/>
                  
<ig:{CategoryChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*In C#*:

[source, cs]
----
dataLegend1.Target = categoryChart1;
dataLegend1.TitleTextColor = Brushes.LightGray;
dataLegend1.LabelTextColor = Brushes.LightGray;
dataLegend1.ValueTextColor = Brushes.Green;
dataLegend1.UnitsTextColor = Brushes.Green;
dataLegend1.UnitsText = "K";
----

endif::wpf,win-forms[]

== Data Legend Value Formatting

The link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] provides automatic abbreviation of large numbers using its link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatAbbreviation.html[ValueFormatAbbreviation] property. This adds a multiplier in the units column such as kilo, million, billion, etc.

You can customize the number of fractional digits that are displayed by setting the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMinFractions.html[ValueFormatMinFractions] and link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMaxFractions.html[ValueFormatMaxFractions]. This will allow you to determine the minimum and maximum number of digits that appear after the decimal point, respectively.

The following code snippet demonstrates how to set the minimum and maximum fractions of the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}]:

ifdef::wpf[]

*In XAML*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                          ValueFormatMinFractions="2"
                          ValueFormatMaxFractions="4"/>
                          
<ig:{CategoryChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*In C#*:

[source, cs]
----
dataLegend1.Target = categoryChart1;
dataLegend1.ValueFormatMinFractions = 2;
dataLegend1.ValueFormatMaxFractions = 4;
----

endif::wpf,win-forms[]

== Data Legend Value Mode

You have the ability to change the default decimal display of values within the link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] to be currency by changing the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMode.html[ValueFormatMode] property of the control. The link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] also exposes the ability to modify the culture of the displayed currency symbol by using its link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatCulture.html[ValueFormatCulture] property and setting it to its corresponding culture tag.

For example, the following code snippet will create a link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] with the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatCulture.html[ValueFormatCulture] set to "en-GB" and the link:{DataChartLink}.{DataLegendName}{ApiProp}ValueFormatMode.html[ValueFormatMode] set to "Currency":

ifdef::wpf[]

*In XAML*:
[source, xaml]
----
<ig:{DataLegendName} Target="{Binding ElementName=chart}"
                  ValueFormatMode="Currency"
                  ValueFormatCulture="en-GB"/>
                  
<ig:{CategoryChartName} x:Name="chart" />
----

endif::wpf[]

ifdef::wpf,win-forms[]

*In C#*:

[source, cs]
----
dataLegend1.Target = categoryChart1;
dataLegend1.ValueFormatMode = Infragistics.Controls.Charts.DataLegendValueMode.Currency;
dataLegend1.ValueFormatCulture = "en-GB";
----

endif::wpf,win-forms[]

== Data Legend Styling Events

The link:{DataChartLink}.{DataLegendName}.html[{DataLegendName}] has three events that fire when rendering their corresponding row. These events are listed below with a description of what they are designed to be used for:

- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleHeaderRow_ev.html[StyleHeaderRow]: This event fires once when rendering the header row.
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesRow_ev.html[StyleSeriesRow]: This event fires once for each series row which allows conditional styling of the values of the series.
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesColumn_ev.html[StyleSeriesColumn]: This event fires once for each series column, which allows conditional styling of the different columns for the series in the chart.
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSummaryRow_ev.html[StyleSummaryRow]: This event fires once when rendering the summary row.
- link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSummaryColumn_ev.html[StyleSummaryColumn]: This event fires once when rendering the summary column.

Each of the above events exposes a link:{DataChartLink}.DataLegendStylingRowEventArgs.html[DataLegendStylingRowEventArgs] parameter as its arguments, which lets you customize each item's text, text color, and the overall visibility of the row. The event arguments also expose event-specific properties. For example, since the link:{DataChartLink}.{DataLegendName}{ApiProp}StyleSeriesRow_ev.html[StyleSeriesRow] event fires for each series, the event arguments will return the series index and series title for the row that represents the series.

The following code snippet demonstrates usage of the above row styling events:

ifdef::wpf,win-forms[]

*In C#*:
[source, cs]
----
private void Legend_StyleSummaryRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.TitleText = "Grand Total: ";
    row.TitleTextColor = Brushes.DimGray;
}

private void Legend_StyleSeriesRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.BadgeShape = Infragistics.Controls.Charts.LegendItemBadgeShape.Square;
    row.TitleText = (row.SeriesIndex + 1) + ". " + row.SeriesTitle;
    row.TitleTextColor = new SolidColorBrush(Colors.DimGray);
}

private void Legend_StyleHeaderRow(object sender, Infragistics.Controls.Charts.DataLegendStylingRowEventArgs row)
{
    row.TitleText = "Date: " + row.TitleText; 
    row.TitleTextColor = Brushes.DimGray;
}
----

endif::wpf,win-forms[]