////
|metadata|
{
    "tags": ["Charting","How Do I","Navigation"],
    "controlName": ["financial-chart"]
}
|metadata|
////

= Chart Navigation

== Topic Overview

=== Purpose

This topic demonstrates, with code examples, the navigation use properties in the link:{FinancialChartLink}.{FinancialChartName}.html[{FinancialChartName}] control and their use.

=== Required background

The following table lists the topics required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:financial-chart-overview.html[{FinancialChartName}]
|This topic provides an overview of the {FinancialChartName} control.

|====

=== In this topic

This topic contains the following sections:

* <<Introduction,Introduction>>
* <<CodeExample,Code Example>>
* <<RelatedContent,Related Content>>

[[Introduction]]
== Introduction

In the {FinancialChartName} control, chart navigation is enabled by default. The following properties can be used to configure navigation behavior.

[options="header", cols="a,a,a,a"]
|====
|Property Name |Property Type 2+|Description

ifdef::wpf[]
|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isHorizontalZoomEnabled{HtmlApiExtension}[IsHorizontalZoomEnabled]
|`boolean`
2+|Whether the chart can be horizontally zoomed through user interactions. By default, this property is set to `true`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isVerticalZoomEnabled{HtmlApiExtension}[IsVerticalZoomEnabled]
|`boolean`
2+|Whether the chart can be vertically zoomed through user interactions. By default, this property is set to `false`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isWindowSyncedToVisibleRange{HtmlApiExtension}[IsWindowSyncedToVisibleRange]
|`boolean`
2+|If set to true the Y-Axis will automatically resize to the visible data range. By default, this property is set to `false`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}windowRect{HtmlApiExtension}[WindowRect]
|`Rect`
2+|Can be used to retrieve or specify the scroll and zoom state in the {FinancialChartName} +
WindowRect is expressed as a Rectangle with coordinates and sizes between 0 and 1.

endif::wpf[]

ifdef::jquery[]
|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isHorizontalZoomEnabled{HtmlApiExtension}[isHorizontalZoomEnabled]
|`bool`
2+|Whether the chart can be horizontally zoomed through user interactions. By default, this property is set to `true`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isVerticalZoomEnabled{HtmlApiExtension}[isVerticalZoomEnabled]
|`bool`
2+|Whether the chart can be vertically zoomed through user interactions. By default, this property is set to `false`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}isWindowSyncedToVisibleRange{HtmlApiExtension}[isWindowSyncedToVisibleRange]
|`bool`
2+|If set to true the Y-Axis will automatically resize to the visible data range. By default, this property is set to `false`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}windowRect{HtmlApiExtension}[windowRect]
|`object`
2+|Can be used to retrieve or specify the scroll and zoom state in the {FinancialChartName} +
WindowRect is expressed as a Rectangle with coordinates and sizes between 0 and 1. +
The provided object should have numeric properties called left, top, width and height.

endif::jquery[]

|====

[[CodeExample]]
== Code Example

The following code snippet demonstrates how to configure chart navigation in the {FinancialChartName} control.

ifdef::jquery[]
*In JavaScript:*
[source,javascript]
----
$(".selector").{FinancialChartName}({
    isWindowSyncedToVisibleRange: true,
    isVerticalZoomEnabled: false,
    isHorizontalZoomEnabled: true
});
----
endif::jquery[]

ifdef::xaml[]
*In XAML:*
[source,xaml]
----
<ig:{FinancialChartName} x:Name="chart"
    IsWindowSyncedToVisibleRange="True"
    IsVerticalZoomEnabled="False"
    IsHorizontalZoomEnabled="True">
</ig:{FinancialChartName}>
----
endif::xaml[]

ifdef::wpf[]
*In C#:*
[source,csharp]
----
var chart = new {FinancialChartName}();
chart.IsWindowSyncedToVisibleRange = true;
chart.IsVerticalZoomEnabled = false;
chart.IsHorizontalZoomEnabled = true;
----

*In Visual Basic:*
[source,vb]
----
Dim chart = New {FinancialChartName}()
chart.IsWindowSyncedToVisibleRange = True
chart.IsVerticalZoomEnabled = False
chart.IsHorizontalZoomEnabled = True
----
endif::wpf[]

[[RelatedContent]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic |Purpose

|link:financial-chart-pane-zoom.html[Zoom Pane]
|This topic provides information on the Zoom Pane of the {FinancialChartName}

|====