////
|metadata|
{
    "tags": ["Charting","Getting Started","How Do I"],
    "controlName": ["financial-chart"]
}
|metadata|
////

= Configuring Axis Scale

The link:{FinancialChartLink}.{FinancialChartName}.html[{FinancialChartName}] control allows you to choose if the data in your charts is mapped logarithmically along the y-axis.

=== In this topic

This topic contains the following sections:

* <<LogarithmicAxis,Logarithmic Axis>>
* <<CodeSnippet, Code Snippet>>
* <<RelatedContent,Related Content>>

[[LogarithmicAxis]]
=== Logarithmic Axis

In the {FinancialChartName} control, you can modify the logarithmic display behavior of the y-axis with these pick:[wpf="properties"]pick:[jquery="options"]:

[options="header", cols="a,a,a,a"]
|====
|pick:[wpf="Property"]pick:[jquery="Option"] Name
|Value Type 
2+|Description

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}yAxisIsLogarithmic{HtmlApiExtension}[pick:[wpf="YAxisIsLogarithmic"]pick:[jquery="yAxisIsLogarithmic"]]
|`bool`
2+|Whether the y-axis should use a logarithmic scale instead of a linear one. The default value is `false`.

|link:{FinancialChartLink}.{FinancialChartName}{ApiProp}yAxisLogarithmBase{HtmlApiExtension}[pick:[wpf="YAxisLogarithmBase"]pick:[jquery="yAxisLogarithmBase"]]
|pick:[wpf="`int`"]pick:[jquery="`number`"]
2+|The base value to use in the log function when mapping the position of data items along the y-axis. +
This is effective only when pick:[wpf="YAxisIsLogarithmic"]pick:[jquery="yAxisIsLogarithmic"] is `true`.

|====

[[CodeSnippet]]
=== Code Snippet

The following code example shows how to set the pick:[wpf="YAxisIsLogarithmic"]pick:[jquery="yAxisIsLogarithmic"] and pick:[wpf="YAxisLogarithmBase"]pick:[jquery="yAxisLogarithmBase"] pick:[wpf="properties"]pick:[jquery="options"]:

ifdef::jquery[]
*In JavaScript:*
[source,javascript]
----
$(".selector").{FinancialChartName}({
    dataSource: data,
    yAxisIsLogarithmic: true,
    yAxisLogarithmBase: 4
});
----
endif::jquery[]

ifdef::wpf[]
*In XAML:*
[source,xaml]
----
<ig:{FinancialChartName} x:Name="chart"  
    YAxisIsLogarithmic="True"
    YAxisLogarithmBase="4">
</ig:{FinancialChartName}>
----

*In C#:*
[source,csharp]
----
var chart = new {FinancialChartName}();
chart.YAxisIsLogarithmic = true;
chart.YAxisLogarithmBase = 4;
----


*In Visual Basic:*
[source,vb]
----
Dim chart = New {FinancialChartName}()
chart.YAxisIsLogarithmic = True
chart.YAxisLogarithmBase = 4
----
endif::wpf[]


[[RelatedContent]]
== Related Content

* link:financial-chart-configuring-axis-labels.html[Configuring Axis Labels]
* link:financial-chart-configuring-axis-modes.html[Configuring Axis Modes]