= Cell and Record Selection

This topic will walk you through the process of configuring cell and record selection in the link:{DataGridLink}.{DataGridName}.html[{DataGridName}] control.

== In this topic

This topic contains the following sections:

* <<ReqBackground,Required Background>>
* <<Overview,Overview>>
* <<SelectionMode,Selection Mode Property>>

[[ReqBackground]]
== Required Background

The following topics are prerequisites to understanding this topic:

|===
|Topic|Purpose

|link:datagrid-getting-started-with-grid.html[Getting Started With {DataGridName}] 
|This topic provides basic steps required for adding the {DataGridName} control to your view and populating it with sample data.

|link:datagrid-working-with-columns.html[Working with Columns]
|This topic provides code examples on working with columns in the {DataGridName} control.

|===

[[Overview]]
== Overview

The {DataGridName} control supports the ability to change how the selection is handled. 

Selection in the data grid is enabled on a row and cell level and can be configured by using the `SelectionMode` option of the grid. This property takes five different options, listed below:

Note, cells and rows selection cannot be enabled together, only separately. 

* SingleCell - Selection of a single cell is enabled.
* SingleRow - Selection of a single row is enabled.
* MultipleCell - Selection of multiple cells is enabled.
* MultipleRow - Selection of multiple rows is enabled.
* RangeCell - Selection of a range of multiple cells by clicking and dragging is enabled.
When set to MultipleRow or MultipleCell, it is not necessary to hold the CTRL key to select multiple rows or cells. Each row or cell will be selected or deselected on click of that particular row or cell.
* None - Disables cell and row selection.

*In XAML:*
[source, xaml]
----
xmlns:ig="clr-namespace:{DataGridNamespace};assembly={ApiPlatform}DataGrid"
...
<ig:{DataGridName} SelectionMode="SingleCell">
</ig:{DataGridName}>
----
endif::xamarin[]

*In C#:*
[source, csharp]
----
{DataGridName} grid = new {DataGridName}() {            
        SelectionMode = GridSelectionMode.SingleCell 
};

----

[[RelatedContent]]
== Related Content

The following table lists topics that are related to this topic:

|===
|Topic|Purpose

|Row Grouping

|This topic provides code examples on grouping rows in the {DataGridName} control.

|===