////
|metadata|
{
    "name": "excelengine-grouping-excel-shapes",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","Grouping"],
    "guid": "e5671d23-2e7a-4019-b66f-8de1ddab1cc3",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7827097Z"
}
|metadata|
////

= Excel の形状のグループ化 ({ExcelEngineName})

== トピックの概要

== 使用目的

このトピックでは、2 つ以上の形状をグループ化する方法を示します。

== 必要な背景

まず以下のトピックを読む必要があります。

* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[形状を Excel ワークシートに追加]

== はじめに

形状グループは、1 つの形状として振る舞う 2 つ以上の形状からなる構造体です。形状のグループを使用した作業は、 link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet.html[Worksheet クラス] および link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape クラス]を使用した作業と似ています。

2つ以上の形状をグループ化するには、形状を初期化し、次に link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup] オブジェクトを初期化して link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroupbase~shapes.html[Shapes] コレクションに形状を追加します。

次の手順は、既に初期化済みの 2 つの形状をグループ化する方法を示します。

== Excel の形状のグループ化

== 要件

手順を完了するには、以下が必要です:

* 2 つの link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape] オブジェクトを初期化します
* この手順の結果を link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet.html[Worksheet] に追加します

== 概要

以下はプロセスの概念的概要です。

[start=1]
. *2 つの形状の初期化*
[start=2]
. *形状のグループ化*
[start=3]
. *位置とサイズを設定します。ワークシートに追加します。*

== 手順

[start=1]
. *2 つの形状の初期化*

オブジェクト名 *shape1* および *shape2。* この手順を完了するには、｢ link:excelengine-adding-a-shape-to-an-excel-worksheet.html[形状を Excel ワークシートに追加]」を参照してください
[start=2]
. *形状のグループ化*

新しい link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup] オブジェクトを初期化し、形状をその link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroupbase~shapes.html[Shapes] コレクションに追加します。

ifdef::wpf[]
*Visual Basic の場合:*
[source,vb]
----
Dim shapeGroup As New WorksheetShapeGroup()
shapeGroup.Shapes.Add(shape1)
shapeGroup.Shapes.Add(shape2)
----
endif::wpf[]

*C# の場合：*
[source,csharp]
----
WorksheetShapeGroup shapeGroup = new WorksheetShapeGroup();
shapeGroup.Shapes.Add(shape1);
shapeGroup.Shapes.Add(shape2);
----

[start=3]
. *位置とサイズを設定します。ワークシートに追加します。*

link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshapegroup.html[WorksheetShapeGroup クラス] は link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetshape.html[WorksheetShape クラス]から派生しているため、サイズ変更、配置、シートへの追加などはすべて link:excelengine-adding-a-shape-to-an-excel-worksheet.html[形状を Excel ワークシートに追加]と同様です。

== 関連トピック

以下は、その他の役立つトピックです。

* link:excelengine-adding-a-shape-to-an-excel-worksheet.html[形状を Excel ワークシートに追加 ({ExcelEngineName})]
* link:excelengine-importing-shapes-from-excel.html[Excel から形状をインポート ({ExcelEngineName})]