////

|metadata|
{
    "name": "excelengine-comments-in-a-worksheet-cell",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{4F1C95A3-66A8-481F-866B-8C6CF0B0225E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= ワークシート セルのコメント

セル コメントは、セルまたはセルの範囲のコンテンツを説明または思い出すために使用されます。たとえば、関連付けられるセル内にある数式を説明するために使用することができます。Microsoft® Excel® の場合のように、Infragistics.Documents.Excel アセンブリの  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcellcomment.html[WorksheetCellComment]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcellcomment.html[WorksheetCellComment]"]  クラスを使用して、セル コメントを Excel ワークシートに追加することができます。

コメントを持つセルは右上隅に赤い三角形が付きます。コメントを見るには、セルにポインタを配置します。セルからポインタを移動すると、コメントが消えます。

以下の例のコードはコメントをセルに追加する方法を表示します。

*Visual Basic の場合：*

----
Dim comment As Infragistics.Documents.Excel.WorksheetCellComment = New WorksheetCellComment () 
Dim formatted As New FormattedString ("This is a comment") 
comment.Text = formatted 
worksheet4.Rows (10).Cells (2).Comment = comment
----

*C# の場合：*

----
Infragistics.Documents.Excel.WorksheetCellComment comment = new WorksheetCellComment ();
FormattedString formatted = new FormattedString ("This is a comment");
comment.Text = formatted;
worksheet4.Rows [10].Cells [2].Comment = comment;
----