////
|metadata|
{
    "name": "excelengine-load-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","Getting Started","How Do I"],
    "guid": "{F630174F-D7A0-4745-91E1-F2A8B643B4EB}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7647061Z"
}
|metadata|
////

= Excel ファイルのロード

ifdef::win-forms,win-forms-old,asp-net,aspnet-old,wpf[]

Microsoft® Excel® ファイルの作成に加えて、{ExcelEngineName} はこれらのファイルを読み取ることもできます。既存の Excel ファイルから link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] オブジェクトを作成し、変更を行い、修正したワークブックを含む新しいファイルを保存することができます。Workbook オブジェクトの静的な link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~load.html[Load] メソッドを使用して Excel ファイルを読み取る時に、Workbook オブジェクトが作成され、オブジェクト モデルに Excel オブジェクト ライブラリによってサポートされるすべての機能が格納されます。ワークブックおよびワークシート オプションだけでなく、セル値およびフォーマットはすべて、解析されたワークブックからアクセスおよび修正可能です。

endif::win-forms,win-forms-old,asp-net,aspnet-old,wpf[]
ifdef::xamarin[]

Microsoft® Excel® ワークブックを作成するだけでなく、{ExcelEngineName} はワークブックを読み取ることもできます。Excel ワークブックを読み込むには、link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] の静的な link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~load.html[Load] メソッドを呼び出し、Excel ワークブック コンテンツ ソースへの入力ストリームを提供します。結果として、Workbook オブジェクトが作成され、そのオブジェクト モデルが {ExcelEngineName} でサポートされるすべての機能と生成されます。ワークブックおよびワークシート オプションだけでなく、すべてのセル値および書式へ解析されたワークブックからアクセスおよび修正が可能です。

endif::xamarin[]

以下のコードの例は既存のワークブックをロードする方法を示します。

ifdef::wpf[]
*Visual Basic の場合：*
[source, vb]
----
Imports Infragistics.Documents.Excel
...
' データを含むワークブックを読み込みます
Dim workbook1 As Workbook = Workbook.Load(pick:[wpf=""filename.xls""]pick:[xamarin="inputStream"])
----
endif::wpf[]

*C# の場合：*
[source, csharp]
----
using Infragistics.Documents.Excel;
...
// データを含むワークブックを読み込みます
Workbook workbook1 = Workbook.Load(pick:[wpf=""filename.xls""]pick:[xamarin="inputStream"]);
----

== 関連トピック

link:excelengine-creating-a-workbook.html[ワークブックを作成]

link:excelengine-save-a-workbook.html[ワークブックの保存]

link:excelengine-format-a-cell.html[セルをフォーマット]

link:excelengine-copy-a-cells-format.html[セルのフォーマットのコピー]

link:excelengine-reference-cells-and-regions.html[セルと領域を参照]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[セルの結合]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[セルの結合]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[数式をセルに追加]

link:excelengine-add-a-comment-to-a-cell.html[コメントをセルに追加]

link:excelengine-disable-editing-of-a-worksheet.html[ワークシートの編集を無効にする]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[行と列をフリーズ]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[行と列をフリーズ ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-set-excel-document-properties.html[Excel ドキュメント プロパティの設定]