////

|metadata|
{
    "name": "excelengine-excel-object-model",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{BC7D9916-09C3-440B-AE57-1FEA1EB4178A}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:19:20Z"
}
|metadata|
////

= Excel オブジェクト モデル

== ワークブック

Infragistics.Documents.Excel アセンブリの基礎は  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  オブジェクトです。Workbook インスタンスがなければ、Microsoft® Excel® ファイルとしてその他の情報を書き出すことはできません。ワークブックはワークシートの集合で、各ワークシートはセルにデータのグリッドを保持します。さらに、ワークブックにはグローバル設定とカスタムビュー、名前を指定した参照およびスタイルのコレクションが含まれます。ワークブックのグローバル設定は、ドキュメントの制作者やワークブックを Excel で開いた時にワークブックの子 MDI を最小化するかどうかなど、ワークブック全体に影響を与えるオプションです。これらのオプションには、Workbook オブジェクトで直接定義されたプリミティブなプロパティ、ワークブックの  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  プロパティと  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~windowoptions.html[WindowOptions]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~windowoptions.html[WindowOptions]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~windowoptions.html[WindowOptions]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~windowoptions.html[WindowOptions]"]  プロパティが含まれています。Workbook から公開されたほとんどのプリミティブ プロパティは、さまざまな数式計算オプションを制御します。

== DocumentProperties

ワークブックの DocumentProperties はワークブックの XLS ファイルを右クリックして、プロパティを表示することによって表示できるプロパティです。これらにはワークブックの作成者、タイトル、サブタイトルなどのワークブックのコンテンツを記述するさまざざまなタグが含まれています。この情報は、特定のバージョンの Excel で編集することも可能です。

== WorkbookWindowOptions

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]  クラスは、Excel で開いた時にワークブックの子 MDI ウィンドウのさまざまな特性だけでなく、ワークシート固有ではないさまざまな表示オプションを制御します。表示オプションは、どのスクロール バーが表示されるのか、ワークシート タブ バーを表示するかしないか、どのタブをタブバーで最初に表示するかなど、異なるワークシートに切り替えても変わらない多くの視覚的エレメントを制御します。

子ウィンドウを制御するオプションには、MDI の親にとっての子ウィンドウの境界と、開いたときにウィンドウを最小化するかしないかが含まれます。数式バーまたはステータスバーを表示するかどうか、またはワークブックの子ウィンドウを最大化するかどうかなど、特定のウィンドウオプションは、WorkbookWindowOptions では制御できません。これらのプロパティはシステム全体にわたるもので、レジストリに Excel によって保存されるからです。ただし、これらのオプションは WorkbookWindowOptions に似た、 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.customview.html[CustomView]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.customview.html[CustomView]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.customview.html[CustomView]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.customview.html[CustomView]"]  の WindowOptions プロパティによって制御できます。その他のオプションに加えて、WorkbookWindowOptions クラスはワークブック内の選択されたワークシートを示すプロパティを持ちます。

== ワークシート

ワークシートはワークブックを埋めます。ワークブックが一度に表示できるのは少なくともひとつのワークシートでなければなりません。ワークシートにはワークブック内の実際のデータが含まれます。各ワークシートはセルのグリッドを保持し、各セルはデータの形式を保持することができるからです。ワークシート上のコレクションと複雑なプロパティは別として、 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]  オブジェクトにはデフォルトの行と列のサイズ、画像背景（ワークシートにタイルされる）およびその名前を変更するためのプロパティが含まれます。

== WorksheetRow

ワークシートによって公開される最も重要なオブジェクトのひとつが WorksheetRow です。ワークシートの各行は、 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]  オブジェクトによって表されます。WorksheetRow インスタンスによって、ワークシートの対応する行を操作できます。さらに、行の各セルは WorksheetRow によって所有されるコレクションに含まれる  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]  インスタンスによって表されます。WorksheetCell にアクセスするためには、親の WorksheetRow を通過する必要があります。WorksheetCell インスタンスのコレクションは  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]  によって所有されません。親行からのコレクションと親列からのコレクション内の各 WorksheetCell インスタンスを保持するのは冗長であるということが唯一の理由です。各セルおよびデフォルトのセル フォーマットに加えて、行の高さ、表示できるかどうか、アウトライン レベルも、WorksheetRow インスタンスでカスタマイズすることができます。

== WorksheetColumn

WorksheetRow と異なり、ワークシートの列がその下にセルを「含む」としても、WorksheetColumn はセルのコレクションを含みません。これは単にセルが属する WorksheetRow インスタンスからセルにアクセスできるからです。WorksheetColumn からセルをアクセス可能にすることも冗長です。WorksheetColumn インスタンスによって、列のデフォルトのセル フォーマット、幅、表示できるかどうか、アウトライン レベルをカスタマイズできます。

== WorksheetCell

ワークシートはセルのグリッドです。各セルは WorksheetCell インスタンスによって表されます。WorksheetCell オブジェクトを使用して、セルの値とフォーマットを設定できます。セルの値は、ワークブックを Excel で開いたときにセルに表示されるものです。その他のセルの値を計算するために、セルの値は数式によって使用することも可能です。