////
|metadata|
{
    "name": "excelengine-reference-cells-and-regions",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting"],
    "guid": "{904B2B76-11A5-4EE1-8B32-1F4B5C0044E6}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7697071Z"
}
|metadata|
////

= セルと領域を参照 ({ExcelEngineName})

Worksheet オブジェクトの link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~getcell.html[GetCell] または link:{ExcelEngineApiLink}infragistics.documents.excel.worksheet~getregion.html[GetRegion] メソッドをそれぞれ呼び出すことによって、 link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell.html[WorksheetCell] オブジェクトまたは link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetregion.html[WorksheetRegion] オブジェクトにアクセスできます。セル参照文字列をパラメーターとして受け取ります。書式を適用するか、数式またはセルのコンテンツを変更するときに、セルへの参照を取得することは便利です。 pick:[win-forms,win-forms-old,asp-net,aspnet-old="link:excelengine-merge-cells.html[セルの結合]"]pick:[wpf,xamarin="link:excelengine-merging-cells.html[セルの結合]"]トピックは、GetRegion メソッドの一般的な使用を紹介します。

以下の例のコードはセルと領域を参照する方法を示します。例のコードは、worksheet1 という名前の Worksheet オブジェクトへの参照があることを前提とします。

ifdef::wpf[]
*Visual Basic の場合：*
[source,vb]
----
Imports Infragistics.Documents.Excel
...
'単一セルにアクセスします。
Dim cellE2 As WorksheetCell = worksheet1.GetCell("E2")
'セルの範囲のアクセスします。
Dim regionG As WorksheetRegion = worksheet1.GetRegion("G1:G10")
----
endif::wpf[]

*C# の場合：*
[source,csharp]
----
using Infragistics.Documents.Excel;
...
//単一セルにアクセスします。
WorksheetCell cellE2 = worksheet1.GetCell("E2");
//セルの範囲のアクセスします。
WorksheetRegion regionG = worksheet1.GetRegion("G1:G10");
----

== 関連トピック

link:excelengine-creating-a-workbook.html[ワークブックを作成]

link:excelengine-load-an-excel-file.html[Excel ファイルのロード]

link:excelengine-save-a-workbook.html[ワークブックの保存]

link:excelengine-format-a-cell.html[セルをフォーマット]

link:excelengine-copy-a-cells-format.html[セルのフォーマットのコピー]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[セルの結合]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[セルの結合]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[数式をセルに追加]

link:excelengine-add-a-comment-to-a-cell.html[コメントをセルに追加]

link:excelengine-disable-editing-of-a-worksheet.html[ワークシートの編集を無効にする]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[行と列をフリーズ]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[行と列をフリーズ ({ExcelEngineName})]
endif::wpf,xamarin[]

link:excelengine-set-excel-document-properties.html[Excel ドキュメント プロパティの設定]