////

|metadata|
{
    "name": "excelengine-write-a-workbook-to-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{79EEEA27-98FC-4115-AE79-4B2C3FF92C1E}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:23:47Z"
}
|metadata|
////

= ワークブックを Excel ファイルに書き出す

すべてのオプションとセル値を設定した後で、ワークブックでしなければならない最後の作業は、ファイルに書き出すことです。こうすることにより、Microsoft® Excel® で開くことができます。これは、 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  オブジェクトの  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Serialize]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Serialize]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Serialize]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Serialize]"]  メソッドを使用して簡単に実行できます。ワークブックをストリームに書き出したり、ワークブック自体で xls ファイルを自動作成するようにすることができます。

[NOTE]
====
*注:* ワークブックを保存する前に、ワークブックには少なくともひとつの表示できるワークシートを含んでいる必要があります。含んでいない場合には、Save メソッドが呼び出されて例外がスローされます。
====

以下のコードは、ワークブックの作成が完了したらワークブックをファイルに書き出す方法を示します。

*Visual Basic の場合：*

----
workbook.Save("C:\Orders.xls")
----

*C# の場合：*

----
workbook.Save( "C:\\Orders.xls" );
----