////

|metadata|
{
    "name": "excelengine-accessing-cells-and-regions-by-their-reference-strings",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{B8228DFD-7B7B-4332-AC1F-F4B84D454524}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 参照文字列でセルおよび領域にアクセス

このトピックによって、Excel® ワークブックのワークシート内でセルと範囲にアクセスする方法をよく知ることができます。Worksheet クラスの  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]  と  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]  メソッドはパラメータとしてセル参照文字列を受け付けます。

以下の例のコードで、Worksheet セルは GetCell メソッドによってアクセスされ、Excel 数式が適用されます。同様に Excel 数式がワークシート内のセルの範囲に適用されます。

*Visual Basic の場合：*

----
'単一セルにアクセスします。
worksheet.GetCell ("C5").ApplyFormula ("=A5*B5")
'セルの範囲のアクセスします。
 worksheet.GetRegion ("G1:G10").ApplyFormula ("=E1*F1")
----

*C# の場合：*

----
//単一セルにアクセスします。
worksheet.GetCell ("C5").ApplyFormula ("=A5*B5");
//セルの範囲のアクセスします。
 worksheet.GetRegion ("G1:G10").ApplyFormula ("=E1*F1");
----