////

|metadata|
{
    "name": "excelengine-add-document-properties-to-a-workbook",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{68A2E8C6-AEE0-406F-AA41-4C23D98A63DD}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:21:11Z"
}
|metadata|
////

= ドキュメント プロパティをワークブックに追加

コンテンツについての情報を提供するさまざまなプロパティが各ワークブック ファイルに関連付けられています。これらのプロパティには以下の情報が含まれています。

* 制作者
* タイトル
* サブタイトル
* キーワード
* カテゴリー
* ステータス
* コメント

この情報は、ワークブック ファイルの [プロパティ] ダイアログ ボックスだけでなく、Microsoft® Excel® インターフェイスからアクセスできます。  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  プロパティを使用することによってシリアル化する前にワークブック内のこの情報を編集できます。

以下のコードは、ワークブックを作成し、  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]  および  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]  pick:[win-forms-old="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]  ドキュメント プロパティを設定する方法を示します。

*Visual Basic の場合：*

----
Dim workbook As New Infragistics.Documents.Excel.Workbook()
workbook.DocumentProperties.Title = "Expense Report"
workbook.DocumentProperties.Status = "Complete"
----

*C# の場合：*

----
Infragistics.Documents.Excel.Workbook workbook = new Infragistics.Documents.Excel.Workbook();
workbook.DocumentProperties.Title = "Expense Report";
workbook.DocumentProperties.Status = "Complete";
----