////

|metadata|
{
    "name": "excelengine-deploying-the-infragistics-excel-engine",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{38316587-060A-41E2-9900-32958D99964D}",
    "buildFlags": [],
    "createdOn": "2007-04-05T08:18:00Z"
}
|metadata|
////

= Infragistics Excel Engine の配備

$$.NET$$ アプリケーションを配備する時、実行ファイルに加えて特定のファイルを配布する必要があります。アプリケーションがひとつ以上の Infragistics要素を含む場合、アプリケーションの一部としてひとつ以上の Infragistics アセンブリ ファイルを配布または配備する必要があります。このトピックでは、再配布する必要があるファイルの概要を述べます。

[NOTE]
====
*注:* このトピックで特に説明されていないファイルは、再配布できないと見なしてください。お使いのInfragistics製品には含まれているがこのトピックで触れていないファイルは、ライセンスで配布を認められていません。そのようなファイルは、ライセンスを許諾されているInfragistics製品がインストールされているマシン以外のマシンに複製したり、移動したり、そのマシンで共有したりすることは禁じられています。
====

アプリケーションを配備するためには、以下のファイルを再配布する必要があります。

[options="header", cols="a,a"]
|====
|ファイル名|説明

|{VersionedApiPlatform}.Excel.v{ProductVersion}.dll
|Infragistics Excel Engine コード ライブラリを含む .NET アセンブリ。

|{VersionedApiPlatform}.Core.v{ProductVersion}.dll
|Infragistics Documents コア ライブラリを含む .NET アセンブリ。

|====