////
|metadata|
{
    "name": "excelengine-format-a-cell",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Editing","Formatting","How Do I"],
    "guid": "{F448B6F1-3C38-4279-AA6B-26D2A1A9C7DB}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7607053Z"
}
|metadata|
////

= セルをフォーマット ({ExcelEngineName})

{ExcelEngineName} によってセルの外観と動作をカスタマイズすることができます。 link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell.html[WorksheetCell]、 link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetrow.html[WorksheetRow]、 link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn] または link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetmergedcellsregion.html[WorksheetMergedCellsRegion] オブジェクトの link:{ExcelEngineApiLink}infragistics.documents.excel.worksheetcell~cellformat.html[CellFormat] プロパティによって公開されるプロパティを設定することによってセルをカスタマイズできます。

セルの外観のあらゆる特性をカスタマイズできます。セルのフォント、背景、境界線だけでなくテキストの配列と回転を設定できます。セルのテキストで文字ごとに異なるフォーマットを適用することさえ可能です。

書式文字列を指定することによってセル値をフォーマットすることも可能です。許容可能な書式文字列は .NET の標準フォーマットおよびフォーマッティング コードに従います。

以下のコードは数値を通貨として表示するためにセルをフォーマットして負の値に赤の色を設定する方法を示します。例のコードは、worksheet1 という名前の Worksheet への参照があることを前提とします。

ifdef::wpf[]
*Visual Basic の場合:*
[source,vb]
----
worksheet1.Columns(2).CellFormat.FormatString = """$""#,##0.00;[red](""$""#,##0.00)"
----
endif::wpf[]

*C# の場合：*
[source,csharp]
----
worksheet1.Columns[2].CellFormat.FormatString = "\"$\"#,##0.00;[red](\"$\"#,##0.00)";
----

== 関連トピック

link:excelengine-about-infragistics-excel-engine.html[{ExcelEngineName} について]

link:excelengine-creating-a-workbook.html[ワークブックを作成]

link:excelengine-load-an-excel-file.html[Excel ファイルのロード]

link:excelengine-save-a-workbook.html[ワークブックの保存]

link:excelengine-copy-a-cells-format.html[セルのフォーマットのコピー]

link:excelengine-reference-cells-and-regions.html[セルと領域を参照]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[セルの結合]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[セルの結合]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[数式をセルに追加]

link:excelengine-add-a-comment-to-a-cell.html[コメントをセルに追加]

link:excelengine-disable-editing-of-a-worksheet.html[ワークシートの編集を無効にする]

link:excelengine-freeze-and-split-panes.html[行と列をフリーズ]

link:excelengine-set-excel-document-properties.html[Excel ドキュメント プロパティの設定]