////
|metadata|
{
    "name": "excelengine-set-excel-document-properties",
    "controlName": ["Infragistics Excel Engine"],
    "tags": ["Exporting","How Do I"],
    "guid": "{8F0D4F9E-95E1-44E1-9E89-D578CF6169A9}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7737079Z"
}
|metadata|
////

= ワークブック プロパティの設定 ({ExcelEngineName})

Microsoft® Excel® ドキュメント プロパティは、ドキュメントの整理および追跡を支援するための情報を提供します。 link:{ExcelEngineApiLink}infragistics.documents.excel.workbook.html[Workbook] オブジェクトの link:{ExcelEngineApiLink}infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties] プロパティを使用して、これらのプロパティを設定するために {ExcelEngineName} を使用できます。使用可能なプロパティは以下のとおりです。

* Author
* Title
* Subject
* Keyword
* Category
* Status
* Comment
* Company
* Manager

以下のコードは、ワークブックを作成し、Title および Status ドキュメント プロパティを設定する方法を示します。

ifdef::wpf[]
*Visual Basic の場合:*
[source, vb]
----
Imports Infragistics.Documents.Excel
...
Dim workbook As New Workbook()
workbook.DocumentProperties.Title = "Expense Report"
workbook.DocumentProperties.Status = "Complete"
----
endif::wpf[]

*C# の場合：*
[source, csharp]
----
using Infragistics.Documents.Excel;
...
Workbook workbook = new Workbook();
workbook.DocumentProperties.Title = "Expense Report";
workbook.DocumentProperties.Status = "Complete";
----

== 関連トピック

link:excelengine-about-infragistics-excel-engine.html[{ExcelEngineName} について]

link:excelengine-creating-a-workbook.html[ワークブックを作成]

link:excelengine-load-an-excel-file.html[Excel ファイルのロード]

link:excelengine-save-a-workbook.html[ワークブックの保存]

link:excelengine-format-a-cell.html[セルをフォーマット]

link:excelengine-copy-a-cells-format.html[セルのフォーマットのコピー]

link:excelengine-reference-cells-and-regions.html[セルと領域を参照]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-merge-cells.html[セルの結合]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-merging-cells.html[セルの結合]
endif::wpf,xamarin[]

link:excelengine-add-a-formula-to-a-cell.html[数式をセルに追加]

link:excelengine-add-a-comment-to-a-cell.html[コメントをセルに追加]

link:excelengine-disable-editing-of-a-worksheet.html[ワークシートの編集を無効にする]

ifdef::win-forms,win-forms-old,asp-net,aspnet-old[]
link:excelengine-freeze-rows-and-columns.html[行と列をフリーズ]
endif::win-forms,win-forms-old,asp-net,aspnet-old[]
ifdef::wpf,xamarin[]
link:excelengine-freeze-and-split-panes.html[行と列をフリーズ ({ExcelEngineName})]
endif::wpf,xamarin[]