////
|metadata|
{
    "name": "excel-engine",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{E6FB9EA1-5649-4078-A890-3FBEA1549CDA}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.0339599Z"
}
|metadata|
////

= {ExcelEngineName}

このセクションは、エンジンの機能とアプリケーションでのエンジンの使用についてのステップバイステップの手順に至るまで {ExcelEngineName} を説明します。

以下のリンクをクリックして、{ExcelEngineName} に関する情報にアクセスします。

== link:excelengine-about-infragistics-excel-engine.html[{ExcelEngineName} について]

このセクションでは、{ExcelEngineName} のオブジェクト モデルおよび機能の理解を深めるための情報を提供します。

== link:excelengine-creating-a-workbook.html[ワークブックを作成]

{ExcelEngineName} を使ってできる限り素早く起動および実行するために、{ExcelEngineName} を使用して開始する方法（ワークブックの作成など）についての情報を提供しています。

== link:excelengine-using-the-infragistics-excel-engine.html[{ExcelEngineName} の使用]

このセクションには、{ExcelEngineName} で提供される主要な特徴および機能についての情報が含まれています。

== link:excelengine-api-overview.html[API の概要]

このトピックは、{ExcelEngineName} でプログラミング中に作業する名前空間とクラスをリストします。このトピックに示されている名前空間とクラスは、{ProductName} ヘルプの link:api-reference-guide.html[API リファレンス] にリンクしており、便利です。