////

|metadata|
{
    "name": "excelengine-getting-the-value-of-a-formula-from-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{DC254CCD-E36D-4C9C-8064-DE6F151EA44B}",  
    "buildFlags": [],
    "createdOn": "2008-11-09T11:33:27Z"
}
|metadata|
////

= Excel ファイルから数式の値を取得

数式によって表される Excel セルの評価された値を取得するには、 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]  の  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell~value.html[Value]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell~value.html[Value]"]  プロパティにアクセスします。

以下のコード例は、Excel 数式によって移植される特定の Excel ワークシート セルのアクセス方法を示します。

*Visual Basic の場合：*

----
lblValue.Text = theWorksheet.Rows[1].Cells[4].Value;
----

*C# の場合：*

----
lblValue.Text = theWorksheet.Rows[1].Cells[4].Value;
----

== 関連トピック

link:excelengine-read-an-excel-file-into-a-workbook.html[Excel ファイルをワークブックに読み取る]

pick:[win-forms="link:wingrid-getting-excel-formula-values-into-wingrid.html[WinGrid に Excel 数式の値を入れる]"]