////

|metadata|
{
    "name": "excelengine-moving-a-worksheet-within-an-excel-workbook",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{620BAB94-A991-471B-A3A3-D7E9418B6FCB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Excel ワークブック内にワークシートを移動

特定のケースで、所有する Excel® ワークブックのワークシート コレクションの特定のインデックス位置にワークシートを移動しなければならない場合があります。

Excel ワークブックに 3 つのワークシートがあるとします。 pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]  クラスの  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~movetoindex.html[MoveToIndex]"]pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~movetoindex.html[MoveToIndex]"]  メソッドを使用して、最初の位置に worksheet3 を配置できます。

以下の例のコードはこれを実装する方法を示します。

*Visual Basic の場合：*

----
Dim workbook As New Infragistics.Documents.Excel.Workbook () 
Dim worksheet1 As Infragistics.Documents.Excel.Worksheet = workbook.Worksheets.Add ("Sheet1") 
Dim worksheet2 As Infragistics.Documents.Excel.Worksheet = workbook.Worksheets.Add ("Sheet2") 
Dim worksheet3 As Infragistics.Documents.Excel.Worksheet = workbook.Worksheets.Add ("Sheet3") 
`Sheet3 を最初の位置に移動します
worksheet3.MoveToIndex (0)
----

*C# の場合：*

----
 Infragistics.Documents.Excel.Workbook workbook = new Infragistics.Documents.Excel.Workbook ();
 Infragistics.Documents.Excel.Worksheet worksheet1 = workbook.Worksheets.Add ("Sheet1");
 Infragistics.Documents.Excel.Worksheet worksheet2 = workbook.Worksheets.Add ("Sheet2");
 Infragistics.Documents.Excel.Worksheet worksheet3 = workbook.Worksheets.Add ("Sheet3");
// Sheet3 を最初の位置に移動します
 worksheet3.MoveToIndex (0);
----