////

|metadata|
{
    "name": "documentengine-welcome-to-infragistics-document-engine",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{1C16F04D-AEEB-49B4-9CAE-BD3F8E515A6E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Infragistics Document Engine にようこそ

Infragistics Document Engine™ は完全な必要なものを完備したコード ライブラリで、Portable Document Format（PDF）と XML Paper Specification（XPS）の両フォーマットで優れたレポートを生成することができます。Infragistics Document Engine の Document Object Model（DOM）は素早く起動して実行するのに十分シンプルでありながら、Infragistics 製品で良く知られているカスタマイズ可能性を提供するために十分複雑です。DOM を使用すると、効果的にレポートを作成、セクションを追加、テキストを追加、レポートをパブリッシュ、すべてを簡単な 4 行のコードで済ませることができます。

== link:documentengine-report-elements.html[レポート エレメント]

レポート エレメントを使用すると、レポートの本文を作成、レイアウトを管理、コンテンツを追加、目次や索引などのナビゲーション ヘルパーを追加することさえ可能です。

== link:documentengine-report-layout.html[レポート レイアウト]

情報のフローと情報をページでどのようにレイアウトするのかを制御します。Sections を使用して、レポート内の論理領域を定義すると、それぞれが固有のヘッダとフッタを含むことができます。Flow エレメントを使用して、列をレポートに追加します。Chain、Rotator、Stretcher などの高度なレイアウト エレメントを使用すると、レポートのレイアウトをより高度に制御することができます。

== link:documentengine-pattern-content.html[パターン コンテンツ]

コンテンツ エレメントは、Tables、Lists、および Trees などの繰り返し可能なコンテンツを追加する方法を提供します。これらのエレメントは、データ ソースと適切に組み合わされます。Table エレメントを使用して、DataSet から Customers の表を複写し、List エレメントを使用して特定のステータスの全顧客をリストし、Tree エレメントを使用して、階層データ ソースを簡略化されたバージョンで表示することができます。

== link:documentengine-quick-content.html[クイック コンテンツ]

テキスト、画像、リスト、または表を素早く追加する必要がある時には、これらの軽量のエレメントが最適です。十分な機能を備えたエレメントほど複雑でありませんが、これらのエレメントは最小限の労力でジョブを完了できます。

== link:documentengine-navigation-helpers.html[ナビゲーション ヘルパー]

500 ページのレポートで不可欠な特定のエレメントがあります。レポートが極端に長い場合、レポートのコンテンツを素早く参照して特定のページにジャンプするために table of contents を設定する支援をします。または、特定の語を見つける必要がある時には、Index は特定の用語が存在する全ページをリストするので便利です。Bookmarks も後で戻りたい重要なページを追跡する際の優れたナビゲーション ヘルパーです。

== link:documentengine-report-graphics.html[レポート グラフィックス]

レポートのレイアウトが決定したら、いくつかのグラフィックス エレメントを使用して外観を改善します。Brushes と Pens を使用して、異なる Colors でエレメントを塗りつぶし、エレメントの境界線の外観を制御します。グラフ、ロゴ、製品などの Images を追加します。Points を使用して複雑なポリゴンの Shapes を作成します。Fonts エレメントを使用して、レポートの多数のフォントを管理します。