////

|metadata|
{
    "name": "documentengine-getting-started-with-infragistics-document-engine",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{CE77953A-8811-461E-9DD1-04B75134F953}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Infragistics Document Engine で開始

Infragistics Document Engine™ はいくつかのインターフェイスを持った複数の名前空間をそれぞれに含んでいる大きいアセンブリです。Documents アセンブリを初めて使用する場合には、その機能を完全に理解しようとして、アセンブリの大きさに若干困惑するかもしれません。このため、Infragistics Document Engine を理解し、固有のシンプルなレポートを作成するために最短のルートを進むことができるように、クイック スタートのトピックを追加しました。

レポートの記述は線形のプロセスであるため、以下のロードマップを使用すると、Document Engine の Document Object Model を理解しやすくなります。

レポート >> セクション >> レイアウト エレメント >> レポート グラフィックス >> パターン コンテンツ >> パブリッシュ

== レポート

pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report.html[Report]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report.html[Report]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report.html[Report]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report.html[Report]"]  オブジェクトは、レポートを作成するために必要なすべてのオブジェクト、プロパティ、情報を含みます。レポート作成の最初のステップは、このオブジェクトをインスタンス化することです。いったんインスタンス化したら、セクションおよびレポート情報を追加し、レポート固有のプロパティを設定して、レポートを保存するか、既存のレポートをロードすることができます。プレファレンス、添付ファイル、埋め込みフォントだけでなく、レポートのブックマークにアクセスすることができます。コンテンツをレポートに追加する準備が整ったら、AddSection メソッドを使用して Section エレメントを追加することができます。

詳細は、 link:documentengine-report.html[「レポート」]を参照してください。

== セクション

Report オブジェクトを取得したら、 pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  オブジェクトの追加が完了するまで一切コンテンツを作成できません。Section エレメントは、レポート自体に追加可能である唯一のレイアウト エレメントであるため独特なエレメントです。その他のすべてのレイアウト エレメント（たとえば、Band、Chain、Flow、および Group）は Section エレメントに追加できます。必要な数だけセクションをレポートに追加してください。複数のヘッダとフッタを追加するだけでなく、追加のページをセクションに追加することができます。Section エレメントが含むことができるレイアウト エレメントおよびコンテンツと、含むことができないレイアウト エレメントおよびコンテンツをしっかりと把握する必要があります。

詳細は link:documentengine-section.html[「セクション」]を参照してください。

== レイアウト エレメント

レポートのコンテンツの構成およびレイアウトを支援する 10 のエレメントがあります。これらのエレメントにはテキスト、画像、表、ツリー、リストなど多くのコンテンツ エレメントを含むことができます。手始めに適したレイアウト エレメントは、Band エレメントです。Band エレメントは Section エレメントと同じように、その他のほとんどのレイアウト エレメントとパターン コンテンツを含むことができます。Band エレメントには繰り返し可能なヘッダ、フッタ、デバイダのコレクションもあります。

詳細は link:documentengine-report-layout.html[「レポート レイアウト」]のセクションを参照してください。またユーザーのニーズに最も適したレイアウト エレメントについては link:documentengine-band.html[「バンド」]のトピックを参照してください。

== レポート グラフィックス

これでレポート記述の基本（レポートの作成、セクションの追加、レイアウト エレメントとコンテンツをこれらのセクションに入れる）が完了したので、レポート グラフィックスを使用することで、レポートを生き生きとさせる必要があります。レポート グラフィックスは、色、グラデーション、単色塗りつぶし、異なるスタイル フォント、すべての形状とサイズの矩形を含むキャンバス、および画像を提供します（画像は百分は一見にしかずです）。Brushes と Pens でレポートのレイアウトに美しさを高めます。Backgrounds と Borders それぞれに Brushes と Pens を使用することができ、読んで楽しいエグゼクティブ レポートを作成するという目的に大きく貢献します。

詳細は link:documentengine-report-graphics.html[「レポート グラフィックス」]を参照してください。すぐに開始したい場合には、 link:documentengine-brushes.html[「ブラシ」]と link:documentengine-pens.html[「ペン」] を参照してください。

== パターン コンテンツ

パターン コンテンツはレポートの中心です。追加したいテキストは、このグループ内のエレメントによって行われます。ここに Text エレメントがあり、任意のスタイルでテキストを追加できます。Grids、Lists、Trees、および Tables を使用して、どのようなデータ ソースを使用していてもそれらから繰り返し可能なコンテンツを形成できます。データセットからデータの表を表示する必要がある場合には、 pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.table.itable.html[ITable]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.table.itable.html[ITable]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.table.itable.html[ITable]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.table.itable.html[ITable]"]  インターフェイスを使用します。レポートにとって重要な名前または製品のリストがありますか? pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.list.ilist.html[IList]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.list.ilist.html[IList]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.list.ilist.html[IList]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.list.ilist.html[IList]"]  インターフェイスを使用してリストを作成します。これらのエレメントは、特定のメソッドによってそれぞれ簡単にレイアウト エレメントに追加できます（ITable インターフェイスの場合は AddTable、IList インターフェイスの場合は AddList）。これらのメソッドは、ほとんどのレイアウト エレメントにあります。

詳細は link:documentengine-pattern-content.html[「パターン コンテンツ」]を参照してください。すぐに開始したい場合には、 link:documentengine-text.html[「テキスト」]のトピックを参照してください。

== パブリッシュ

レポートの記述が終わったら、誰かと共有しなければならない場合があります。レポートをパブリッシュする方法は、いくつかの要因によって異なります。パブリッシュの方法を見てみましょう。

*印刷* – 最も簡単なパブリッシュの方法です。Report オブジェクトから  pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~print.html[Print]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~print.html[Print]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~print.html[Print]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~print.html[Print]"]  を呼び出すと、レポートをローカル プリンタに直接印刷することができます。

*パブリッシュ* – 「パブリッシュ」という語は、PDF または XPS ファイルにレポートを書き出すことを指します。この方法は、Adobe Acrobat® PDF Writer を使用して、 Microsoft® Word ドキュメントを出力することと同じです。

*XML で保存* – レポート コンテンツ全体を XML ファイルに保存するオプションが提供されています。これによって、完成したレポート全体を保存して後でロードすることができます。パブリッシュした後でレポートに追加や修正が必要なことが分かった場合に役に立ちます。

*生成* – このパブリッシュ方法は独特で若干変わっていますが非常に役に立ちます。Report オブジェクトの  pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~generate.html[Generate]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~generate.html[Generate]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~generate.html[Generate]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~generate.html[Generate]"]  メソッドを使用すると、大量のページ セットで構成されるグラフィックス オブジェクトをレポートから作成します。これらのグラフィックス オブジェクトは、レポートのページのサムネイル画像として使用することができます。

詳細は、 link:documentengine-publish-a-report.html[「レポートをパブリッシュ」]を参照してください。