////

|metadata|
{
    "name": "documentengine-quick-image",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{2FE53039-F852-4F0B-8A77-DCD1E9B52BE3}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= クイック画像

Quick Image エレメントによって、わずかまたはまったく努力せずにほとんどのレイアウト エレメントに画像を追加できます。画像をレポートに素早く追加するために必要なのは、画像を挿入する必要があるいずれのレイアウト エレメントでも AddQuickImage メソッドを呼び出すことだけです。このメソッドが持つパラメータは、 pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Reports.Graphics.Image]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Reports.Graphics.Image]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Reports.Graphics.Image]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Reports.Graphics.Image]"]  ひとつだけです。以前に作成した画像を渡す、または新しい画像をインスタンス化するのいずれかを実行できます。詳細については、「画像」を参照してください。

以下のコードは、 pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  インターフェイスから  pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]  メソッドを呼び出して新しい画像を渡すことによって、Quick Image エレメントを作成します。新しい画像は 2 番目のオーバーロードを使用して、画像のパスを識別するために文字列を使用します。このトピックは、Report エレメントを定義済みでこのエレメントに少なくともひとつの Section エレメントを追加してあることを前提とします。詳細は、 link:documentengine-report.html[「レポート」]および link:documentengine-section.html[「セクション」]を参照してください。

*Visual Basic の場合：*

----
section1.AddQuickImage(New Image(Application.StartupPath + "..\Coffee Bean.bmp"))
----

*C# の場合：*

----
section1.AddQuickImage(new Image(Application.StartupPath + @"..\Coffee Bean.bmp"));
----