////

|metadata|
{
    "name": "documentengine-setting-pageorientation-when-publishing-a-report",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{34717629-DE75-4810-B4F8-F0AF5921DF7F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= レポートのパブリッシュ時に PageOrientation を設定

PDF または XPS ドキュメントを発行する時、ページの方向は  pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~pageorientation.html[PageOrientation]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~pageorientation.html[PageOrientation]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~pageorientation.html[PageOrientation]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~pageorientation.html[PageOrientation]"]  プロパティによって設定できます。 pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~publish.html[Report.Publish()]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~publish.html[Report.Publish()]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.report~publish.html[Report.Publish()]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.report~publish.html[Report.Publish()]"]  メソッドが使用されると、Report に追加する各 Section  pick:[win-forms="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection()]"]  pick:[asp-net="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection()]"]  pick:[win-forms-old="link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection()]"]  pick:[aspnet-old="link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection()]"]  で PageOrientation を直接設定する必要があります。

*Visual Basic の場合：*

----
Dim r As Infragistics.Documents.Reports.Reports.Report.Report = New Report()
' セクションを Report に追加します。 
Dim s As Infragistics.Documents.Reports.Reports.Report.Section.ISection = r.AddSection()
s.PageOrientation = PageOrientation.Portrait 
'Section に Text を追加します。 
Dim t As Infragistics.Documents.Reports.Reports.Report.Text.IText = s.AddText()
t.AddContent(”Test Text”) 
Dim theFile As String = c:\test.pdf”
r.Publish(theFile, FileFormat.PDF)
----

*C# の場合：*

----
Infragistics.Documents.Reports.Reports.Report.Report r = new Report();
//セクションを Report に追加します。
Infragistics.Documents.Reports.Reports.Report.Section.ISection s = r.AddSection();
 s.PageOrientation = PageOrientation.Portrait;
 //Section に Text を追加します。
 Infragistics.Documents.Reports.Reports.Report.Text.IText t = s.AddText();
 t.AddContent(”Test Text”);
 string theFile = @”c:\test.pdf”;
 r.Publish(theFile, FileFormat.PDF);
----